# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogASDUtility.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HxToolsDialog(object):
    def setupUi(self, HxToolsDialog):
        HxToolsDialog.setObjectName("HxToolsDialog")
        HxToolsDialog.resize(721, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HxToolsDialog.sizePolicy().hasHeightForWidth())
        HxToolsDialog.setSizePolicy(sizePolicy)
        HxToolsDialog.setMinimumSize(QtCore.QSize(0, 91))
        self.gridLayout_3 = QtWidgets.QGridLayout(HxToolsDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(HxToolsDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.outSelector = GdalToolsInOutSelector(self.groupBox_2)
        self.outSelector.setEnabled(True)
        self.outSelector.setObjectName("outSelector")
        self.gridLayout_2.addWidget(self.outSelector, 1, 1, 1, 1)
        self.inHDRSelector = GdalToolsInOutSelector(self.groupBox_2)
        self.inHDRSelector.setEnabled(True)
        self.inHDRSelector.setObjectName("inHDRSelector")
        self.gridLayout_2.addWidget(self.inHDRSelector, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(HxToolsDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.RAW = QtWidgets.QRadioButton(self.groupBox_3)
        self.RAW.setObjectName("RAW")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(HxToolsDialog)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.RAW)
        self.verticalLayout.addWidget(self.RAW)
        self.REF = QtWidgets.QRadioButton(self.groupBox_3)
        self.REF.setObjectName("REF")
        self.buttonGroup_2.addButton(self.REF)
        self.verticalLayout.addWidget(self.REF)
        self.RAD = QtWidgets.QRadioButton(self.groupBox_3)
        self.RAD.setObjectName("RAD")
        self.buttonGroup_2.addButton(self.RAD)
        self.verticalLayout.addWidget(self.RAD)
        self.REFL = QtWidgets.QRadioButton(self.groupBox_3)
        self.REFL.setChecked(True)
        self.REFL.setObjectName("REFL")
        self.buttonGroup_2.addButton(self.REFL)
        self.verticalLayout.addWidget(self.REFL)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(HxToolsDialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ASD = QtWidgets.QRadioButton(self.groupBox_4)
        self.ASD.setChecked(True)
        self.ASD.setObjectName("ASD")
        self.buttonGroup = QtWidgets.QButtonGroup(HxToolsDialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.ASD)
        self.verticalLayout_2.addWidget(self.ASD)
        self.AVIRISNG = QtWidgets.QRadioButton(self.groupBox_4)
        self.AVIRISNG.setChecked(False)
        self.AVIRISNG.setObjectName("AVIRISNG")
        self.buttonGroup.addButton(self.AVIRISNG)
        self.verticalLayout_2.addWidget(self.AVIRISNG)
        self.LISS4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.LISS4.setObjectName("LISS4")
        self.buttonGroup.addButton(self.LISS4)
        self.verticalLayout_2.addWidget(self.LISS4)
        self.SENTINEL = QtWidgets.QRadioButton(self.groupBox_4)
        self.SENTINEL.setObjectName("SENTINEL")
        self.buttonGroup.addButton(self.SENTINEL)
        self.verticalLayout_2.addWidget(self.SENTINEL)
        self.LANDSAT = QtWidgets.QRadioButton(self.groupBox_4)
        self.LANDSAT.setObjectName("LANDSAT")
        self.buttonGroup.addButton(self.LANDSAT)
        self.verticalLayout_2.addWidget(self.LANDSAT)
        self.OTHER = QtWidgets.QRadioButton(self.groupBox_4)
        self.OTHER.setObjectName("OTHER")
        self.buttonGroup.addButton(self.OTHER)
        self.verticalLayout_2.addWidget(self.OTHER)
        self.insrfSelector = GdalToolsInOutSelector(self.groupBox_4)
        self.insrfSelector.setEnabled(False)
        self.insrfSelector.setObjectName("insrfSelector")
        self.verticalLayout_2.addWidget(self.insrfSelector)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.groupBox = QtWidgets.QGroupBox(HxToolsDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mplWidget = QMatplotlibWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplWidget.sizePolicy().hasHeightForWidth())
        self.mplWidget.setSizePolicy(sizePolicy)
        self.mplWidget.setObjectName("mplWidget")
        self.gridLayout_5.addWidget(self.mplWidget, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 318, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_bbl = QtWidgets.QRadioButton(HxToolsDialog)
        self.radioButton_bbl.setEnabled(False)
        self.radioButton_bbl.setObjectName("radioButton_bbl")
        self.horizontalLayout_2.addWidget(self.radioButton_bbl)
        self.inbblSelector = GdalToolsInOutSelector(HxToolsDialog)
        self.inbblSelector.setEnabled(False)
        self.inbblSelector.setMouseTracking(False)
        self.inbblSelector.setObjectName("inbblSelector")
        self.horizontalLayout_2.addWidget(self.inbblSelector)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.checkBox = QtWidgets.QCheckBox(HxToolsDialog)
        self.checkBox.setEnabled(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QPlainTextEdit(HxToolsDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMinimumSize(QtCore.QSize(91, 91))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_3.addWidget(self.textBrowser, 3, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(HxToolsDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 4, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(HxToolsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 5, 0, 1, 1)
        self.label.setBuddy(self.insrfSelector)

        self.retranslateUi(HxToolsDialog)
        QtCore.QMetaObject.connectSlotsByName(HxToolsDialog)

    def retranslateUi(self, HxToolsDialog):
        _translate = QtCore.QCoreApplication.translate
        HxToolsDialog.setWindowTitle(_translate("HxToolsDialog", "ASD Utility"))
        self.groupBox_2.setTitle(_translate("HxToolsDialog", "I/O"))
        self.label.setText(_translate("HxToolsDialog", "Input ASD file (or files)"))
        self.label_3.setText(_translate("HxToolsDialog", "Output file"))
        self.groupBox_3.setTitle(_translate("HxToolsDialog", "Type of Spectrum"))
        self.RAW.setText(_translate("HxToolsDialog", "Raw Spectrum"))
        self.REF.setText(_translate("HxToolsDialog", "Reference Spectrum"))
        self.RAD.setText(_translate("HxToolsDialog", "Radiance Spectrum"))
        self.REFL.setText(_translate("HxToolsDialog", "Reflectance Spectrum"))
        self.groupBox_4.setTitle(_translate("HxToolsDialog", "Select Type of Sensor for Resampling"))
        self.ASD.setText(_translate("HxToolsDialog", "ASD"))
        self.AVIRISNG.setText(_translate("HxToolsDialog", "AVIRIS-NG "))
        self.LISS4.setText(_translate("HxToolsDialog", "LISS-4"))
        self.SENTINEL.setText(_translate("HxToolsDialog", "Sentinel-2 MSI"))
        self.LANDSAT.setText(_translate("HxToolsDialog", "LANDSAT 8 OLI"))
        self.OTHER.setText(_translate("HxToolsDialog", "Other Sensor (Select SRF \'.xlsx\' File)"))
        self.groupBox.setTitle(_translate("HxToolsDialog", "Spectrum Viewer"))
        self.radioButton_bbl.setText(_translate("HxToolsDialog", "AVIRIS Bad Band *.hdr file"))
        self.inbblSelector.setToolTip(_translate("HxToolsDialog", "Enter the HDR file with badband header"))
        self.inbblSelector.setWhatsThis(_translate("HxToolsDialog", "Enter the HDR file with badband header"))
        self.checkBox.setText(_translate("HxToolsDialog", "Jump Correction"))
        self.buttonBox.setToolTip(_translate("HxToolsDialog", "<html><head/><body><p>Generate Spectra &amp; SAVE</p></body></html>"))

from HxTools.ui.inOutSelector import GdalToolsInOutSelector
from HxTools.ui.qmatplotlibwidget import QMatplotlibWidget
