# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui\Multivariate_RegressionUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 619)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setObjectName("label_71")
        self.gridLayout.addWidget(self.label_71, 1, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setEnabled(True)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_44 = QtWidgets.QWidget()
        self.tab_44.setObjectName("tab_44")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.tab_44)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.splitter = QtWidgets.QSplitter(self.tab_44)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_2.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout_2.addWidget(self.radioButton_3, 0, 2, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout_2.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.gridLayout_2.addWidget(self.radioButton_7, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        self.label_76.setObjectName("label_76")
        self.verticalLayout.addWidget(self.label_76)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_77 = QtWidgets.QLabel(self.groupBox_2)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_3.addWidget(self.label_77)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.radioButton_5)
        self.verticalLayout_3.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setChecked(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup_2.addButton(self.radioButton_6)
        self.verticalLayout_3.addWidget(self.radioButton_6)
        spacerItem = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_35 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_35.setTitle("")
        self.groupBox_35.setObjectName("groupBox_35")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_35)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout.addWidget(self.radioButton_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_75 = QtWidgets.QLabel(self.groupBox_35)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_2.addWidget(self.label_75)
        self.componentSb = QtWidgets.QSpinBox(self.groupBox_35)
        self.componentSb.setObjectName("componentSb")
        self.verticalLayout_2.addWidget(self.componentSb)
        self.label = QtWidgets.QLabel(self.groupBox_35)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.testSizeSb = QtWidgets.QSpinBox(self.groupBox_35)
        self.testSizeSb.setObjectName("testSizeSb")
        self.verticalLayout_2.addWidget(self.testSizeSb)
        self.label_78 = QtWidgets.QLabel(self.groupBox_35)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_2.addWidget(self.label_78)
        self.crossValSb = QtWidgets.QSpinBox(self.groupBox_35)
        self.crossValSb.setObjectName("crossValSb")
        self.verticalLayout_2.addWidget(self.crossValSb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2.addWidget(self.groupBox_35)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.mplWidgetSpectral_6 = QMatplotlibWidget(self.splitter)
        self.mplWidgetSpectral_6.setObjectName("mplWidgetSpectral_6")
        self.verticalLayout_14.addWidget(self.splitter)
        self.tabWidget_4.addTab(self.tab_44, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.splitter_2 = QtWidgets.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_14 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_14.setObjectName("groupBox_14")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_14)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.radioButton_37 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_37.setChecked(True)
        self.radioButton_37.setObjectName("radioButton_37")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.radioButton_37)
        self.gridLayout_12.addWidget(self.radioButton_37, 0, 0, 1, 1)
        self.radioButton_38 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_38.setObjectName("radioButton_38")
        self.buttonGroup_4.addButton(self.radioButton_38)
        self.gridLayout_12.addWidget(self.radioButton_38, 0, 1, 1, 1)
        self.radioButton_39 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_39.setObjectName("radioButton_39")
        self.buttonGroup_4.addButton(self.radioButton_39)
        self.gridLayout_12.addWidget(self.radioButton_39, 0, 2, 1, 1)
        self.radioButton_40 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_40.setObjectName("radioButton_40")
        self.buttonGroup_4.addButton(self.radioButton_40)
        self.gridLayout_12.addWidget(self.radioButton_40, 1, 0, 1, 1)
        self.radioButton_41 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_41.setObjectName("radioButton_41")
        self.buttonGroup_4.addButton(self.radioButton_41)
        self.gridLayout_12.addWidget(self.radioButton_41, 1, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_14)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_15 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_91 = QtWidgets.QLabel(self.groupBox_15)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_20.addWidget(self.label_91)
        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_15)
        self.comboBox_5.setObjectName("comboBox_5")
        self.verticalLayout_20.addWidget(self.comboBox_5)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_92 = QtWidgets.QLabel(self.groupBox_15)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_21.addWidget(self.label_92)
        self.radioButton_42 = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_42.setChecked(True)
        self.radioButton_42.setObjectName("radioButton_42")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.radioButton_42)
        self.verticalLayout_21.addWidget(self.radioButton_42)
        self.radioButton_43 = QtWidgets.QRadioButton(self.groupBox_15)
        self.radioButton_43.setObjectName("radioButton_43")
        self.buttonGroup_6.addButton(self.radioButton_43)
        self.verticalLayout_21.addWidget(self.radioButton_43)
        spacerItem2 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem2)
        self.verticalLayout_19.addLayout(self.verticalLayout_21)
        self.horizontalLayout_9.addWidget(self.groupBox_15)
        self.groupBox_39 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_39.setTitle("")
        self.groupBox_39.setObjectName("groupBox_39")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_39)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_93 = QtWidgets.QLabel(self.groupBox_39)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_8.addWidget(self.label_93)
        self.compStackedSb = QtWidgets.QSpinBox(self.groupBox_39)
        self.compStackedSb.setObjectName("compStackedSb")
        self.verticalLayout_8.addWidget(self.compStackedSb)
        self.label_5 = QtWidgets.QLabel(self.groupBox_39)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.testSizeStackedSb = QtWidgets.QSpinBox(self.groupBox_39)
        self.testSizeStackedSb.setObjectName("testSizeStackedSb")
        self.verticalLayout_8.addWidget(self.testSizeStackedSb)
        self.label_94 = QtWidgets.QLabel(self.groupBox_39)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_8.addWidget(self.label_94)
        self.crossValStackedSb = QtWidgets.QSpinBox(self.groupBox_39)
        self.crossValStackedSb.setObjectName("crossValStackedSb")
        self.verticalLayout_8.addWidget(self.crossValStackedSb)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem3)
        self.horizontalLayout_9.addWidget(self.groupBox_39)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.mplWidgetSpectral_9 = QMatplotlibWidget(self.splitter_2)
        self.mplWidgetSpectral_9.setObjectName("mplWidgetSpectral_9")
        self.verticalLayout_10.addWidget(self.splitter_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.tabWidget_4.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.groupBox_17 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_17.setObjectName("groupBox_17")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.groupBox_17)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_18 = QtWidgets.QGridLayout()
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.radioButton_46 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_46.setChecked(True)
        self.radioButton_46.setObjectName("radioButton_46")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.radioButton_46)
        self.gridLayout_18.addWidget(self.radioButton_46, 0, 0, 1, 1)
        self.radioButton_47 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_47.setObjectName("radioButton_47")
        self.buttonGroup_5.addButton(self.radioButton_47)
        self.gridLayout_18.addWidget(self.radioButton_47, 0, 1, 1, 1)
        self.radioButton_48 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_48.setObjectName("radioButton_48")
        self.buttonGroup_5.addButton(self.radioButton_48)
        self.gridLayout_18.addWidget(self.radioButton_48, 0, 2, 1, 1)
        self.radioButton_49 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_49.setObjectName("radioButton_49")
        self.buttonGroup_5.addButton(self.radioButton_49)
        self.gridLayout_18.addWidget(self.radioButton_49, 1, 0, 1, 1)
        self.radioButton_50 = QtWidgets.QRadioButton(self.groupBox_17)
        self.radioButton_50.setObjectName("radioButton_50")
        self.buttonGroup_5.addButton(self.radioButton_50)
        self.gridLayout_18.addWidget(self.radioButton_50, 1, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_18, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.groupBox_18 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_95 = QtWidgets.QLabel(self.groupBox_18)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_24.addWidget(self.label_95)
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_18)
        self.comboBox_6.setObjectName("comboBox_6")
        self.verticalLayout_24.addWidget(self.comboBox_6)
        self.verticalLayout_23.addLayout(self.verticalLayout_24)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_96 = QtWidgets.QLabel(self.groupBox_18)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_25.addWidget(self.label_96)
        self.radioButton_51 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_51.setChecked(True)
        self.radioButton_51.setObjectName("radioButton_51")
        self.buttonGroup_8 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_8.setObjectName("buttonGroup_8")
        self.buttonGroup_8.addButton(self.radioButton_51)
        self.verticalLayout_25.addWidget(self.radioButton_51)
        self.radioButton_52 = QtWidgets.QRadioButton(self.groupBox_18)
        self.radioButton_52.setChecked(False)
        self.radioButton_52.setObjectName("radioButton_52")
        self.buttonGroup_8.addButton(self.radioButton_52)
        self.verticalLayout_25.addWidget(self.radioButton_52)
        spacerItem5 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_25.addItem(spacerItem5)
        self.verticalLayout_23.addLayout(self.verticalLayout_25)
        self.horizontalLayout_10.addWidget(self.groupBox_18)
        self.groupBox_40 = QtWidgets.QGroupBox(self.layoutWidget1)
        self.groupBox_40.setTitle("")
        self.groupBox_40.setObjectName("groupBox_40")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_40)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_97 = QtWidgets.QLabel(self.groupBox_40)
        self.label_97.setObjectName("label_97")
        self.verticalLayout_11.addWidget(self.label_97)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_40)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_11.addWidget(self.comboBox_2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_40)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.testSizeSvSb = QtWidgets.QSpinBox(self.groupBox_40)
        self.testSizeSvSb.setObjectName("testSizeSvSb")
        self.verticalLayout_11.addWidget(self.testSizeSvSb)
        self.label_98 = QtWidgets.QLabel(self.groupBox_40)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_11.addWidget(self.label_98)
        self.crossValSvSb = QtWidgets.QSpinBox(self.groupBox_40)
        self.crossValSvSb.setObjectName("crossValSvSb")
        self.verticalLayout_11.addWidget(self.crossValSvSb)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem6)
        self.horizontalLayout_10.addWidget(self.groupBox_40)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.mplWidgetSpectral_10 = QMatplotlibWidget(self.splitter_3)
        self.mplWidgetSpectral_10.setObjectName("mplWidgetSpectral_10")
        self.verticalLayout_13.addWidget(self.splitter_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.tabWidget_4.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget_4, 3, 0, 1, 3)
        self.verticalLayout_7.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Timeseries Analysis"))
        self.groupBox.setTitle(_translate("Form", "Multivariate Regression"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.label_71.setText(_translate("Form", "Metadata"))
        self.label_70.setText(_translate("Form", "Spectra"))
        self.pushButton_4.setText(_translate("Form", "Browse"))
        self.label_72.setText(_translate("Form", "Output"))
        self.pushButton_5.setText(_translate("Form", "Browse"))
        self.groupBox_3.setTitle(_translate("Form", "Spectra Transform(X)"))
        self.radioButton.setText(_translate("Form", "Transform 1/Log"))
        self.radioButton_2.setText(_translate("Form", "Transform Standard Scalar"))
        self.radioButton_3.setText(_translate("Form", "Transform Standard Normal Variate"))
        self.radioButton_4.setText(_translate("Form", "Savitsky-Golay"))
        self.radioButton_7.setText(_translate("Form", "None"))
        self.groupBox_2.setTitle(_translate("Form", "Dependent Variable (y)"))
        self.label_76.setText(_translate("Form", "Select target property"))
        self.label_77.setText(_translate("Form", "Normalize"))
        self.radioButton_5.setText(_translate("Form", "Yes"))
        self.radioButton_6.setText(_translate("Form", "No"))
        self.radioButton_8.setText(_translate("Form", "Validation"))
        self.radioButton_9.setText(_translate("Form", "Testing"))
        self.label_75.setText(_translate("Form", "Number of Components"))
        self.label.setText(_translate("Form", "Sample Test Size (%)"))
        self.label_78.setText(_translate("Form", "Cross Validation : N Fold"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_44), _translate("Form", "PLSRegression"))
        self.groupBox_14.setTitle(_translate("Form", "Spectra Transform(X)"))
        self.radioButton_37.setText(_translate("Form", "Transform 1/Log"))
        self.radioButton_38.setText(_translate("Form", "Transform Standard Scalar"))
        self.radioButton_39.setText(_translate("Form", "Transform Standard Normal Variate"))
        self.radioButton_40.setText(_translate("Form", "Savitsky-Golay"))
        self.radioButton_41.setText(_translate("Form", "None"))
        self.groupBox_15.setTitle(_translate("Form", "Dependent Variable (y)"))
        self.label_91.setText(_translate("Form", "Select target property"))
        self.label_92.setText(_translate("Form", "Normalize"))
        self.radioButton_42.setText(_translate("Form", "Yes"))
        self.radioButton_43.setText(_translate("Form", "No"))
        self.label_93.setText(_translate("Form", "Number of Components"))
        self.label_5.setText(_translate("Form", "Sample Test Size (%)"))
        self.label_94.setText(_translate("Form", "Cross Validation : N Fold"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab), _translate("Form", "Stacked Regression"))
        self.groupBox_17.setTitle(_translate("Form", "Spectra Transform(X)"))
        self.radioButton_46.setText(_translate("Form", "Transform 1/Log"))
        self.radioButton_47.setText(_translate("Form", "Transform Standard Scalar"))
        self.radioButton_48.setText(_translate("Form", "Transform Standard Normal Variate"))
        self.radioButton_49.setText(_translate("Form", "Savitsky-Golay"))
        self.radioButton_50.setText(_translate("Form", "None"))
        self.groupBox_18.setTitle(_translate("Form", "Dependent Variable (y)"))
        self.label_95.setText(_translate("Form", "Select target property"))
        self.label_96.setText(_translate("Form", "Normalize"))
        self.radioButton_51.setText(_translate("Form", "Yes"))
        self.radioButton_52.setText(_translate("Form", "No"))
        self.label_97.setText(_translate("Form", "Choose the Kernel"))
        self.label_6.setText(_translate("Form", "Sample Test Size (%)"))
        self.label_98.setText(_translate("Form", "Cross Validation : N Fold"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_2), _translate("Form", "SV Regression"))

from Ui.qmatplotlibwidget import QMatplotlibWidget
