# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Ui/ProsailUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1014, 578)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_9.addWidget(self.label)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.groupBox_6)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_8.addWidget(self.pushButton_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_4 = QtWidgets.QLabel(self.groupBox_6)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_20.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_20.addWidget(self.lineEdit_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_20.addWidget(self.pushButton_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.verticalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.checkBox)
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.CheckBox_p1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p1.setText("")
        self.CheckBox_p1.setObjectName("CheckBox_p1")
        self.buttonGroup.addButton(self.CheckBox_p1)
        self.horizontalLayout_2.addWidget(self.CheckBox_p1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_3)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_2.addWidget(self.label_43)
        self.horizontalLayout_17.addLayout(self.horizontalLayout_2)
        self.label_56 = QtWidgets.QLabel(self.groupBox_3)
        self.label_56.setObjectName("label_56")
        self.horizontalLayout_17.addWidget(self.label_56)
        self.lineEdit_p1 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p1.setObjectName("lineEdit_p1")
        self.horizontalLayout_17.addWidget(self.lineEdit_p1)
        self.label_69 = QtWidgets.QLabel(self.groupBox_3)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_17.addWidget(self.label_69)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CheckBox_p2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p2.setText("")
        self.CheckBox_p2.setObjectName("CheckBox_p2")
        self.buttonGroup.addButton(self.CheckBox_p2)
        self.horizontalLayout_3.addWidget(self.CheckBox_p2)
        self.label_44 = QtWidgets.QLabel(self.groupBox_3)
        self.label_44.setObjectName("label_44")
        self.horizontalLayout_3.addWidget(self.label_44)
        self.horizontalLayout_18.addLayout(self.horizontalLayout_3)
        self.label_57 = QtWidgets.QLabel(self.groupBox_3)
        self.label_57.setObjectName("label_57")
        self.horizontalLayout_18.addWidget(self.label_57)
        self.lineEdit_p2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p2.setObjectName("lineEdit_p2")
        self.horizontalLayout_18.addWidget(self.lineEdit_p2)
        self.label_70 = QtWidgets.QLabel(self.groupBox_3)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout_18.addWidget(self.label_70)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.CheckBox_p3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p3.setText("")
        self.CheckBox_p3.setObjectName("CheckBox_p3")
        self.buttonGroup.addButton(self.CheckBox_p3)
        self.horizontalLayout_4.addWidget(self.CheckBox_p3)
        self.label_45 = QtWidgets.QLabel(self.groupBox_3)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_4.addWidget(self.label_45)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_4)
        self.label_58 = QtWidgets.QLabel(self.groupBox_3)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_19.addWidget(self.label_58)
        self.lineEdit_p3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p3.setObjectName("lineEdit_p3")
        self.horizontalLayout_19.addWidget(self.lineEdit_p3)
        self.label_71 = QtWidgets.QLabel(self.groupBox_3)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_19.addWidget(self.label_71)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.CheckBox_p4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p4.setText("")
        self.CheckBox_p4.setObjectName("CheckBox_p4")
        self.buttonGroup.addButton(self.CheckBox_p4)
        self.horizontalLayout_5.addWidget(self.CheckBox_p4)
        self.label_46 = QtWidgets.QLabel(self.groupBox_3)
        self.label_46.setObjectName("label_46")
        self.horizontalLayout_5.addWidget(self.label_46)
        self.horizontalLayout_22.addLayout(self.horizontalLayout_5)
        self.label_59 = QtWidgets.QLabel(self.groupBox_3)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_22.addWidget(self.label_59)
        self.lineEdit_p4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p4.setObjectName("lineEdit_p4")
        self.horizontalLayout_22.addWidget(self.lineEdit_p4)
        self.label_72 = QtWidgets.QLabel(self.groupBox_3)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_22.addWidget(self.label_72)
        self.verticalLayout.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.CheckBox_p5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p5.setText("")
        self.CheckBox_p5.setObjectName("CheckBox_p5")
        self.buttonGroup.addButton(self.CheckBox_p5)
        self.horizontalLayout_6.addWidget(self.CheckBox_p5)
        self.label_47 = QtWidgets.QLabel(self.groupBox_3)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_6.addWidget(self.label_47)
        self.horizontalLayout_23.addLayout(self.horizontalLayout_6)
        self.label_60 = QtWidgets.QLabel(self.groupBox_3)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_23.addWidget(self.label_60)
        self.lineEdit_p5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p5.setObjectName("lineEdit_p5")
        self.horizontalLayout_23.addWidget(self.lineEdit_p5)
        self.label_73 = QtWidgets.QLabel(self.groupBox_3)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_23.addWidget(self.label_73)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.CheckBox_p6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p6.setText("")
        self.CheckBox_p6.setObjectName("CheckBox_p6")
        self.buttonGroup.addButton(self.CheckBox_p6)
        self.horizontalLayout_9.addWidget(self.CheckBox_p6)
        self.label_48 = QtWidgets.QLabel(self.groupBox_3)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_9.addWidget(self.label_48)
        self.horizontalLayout_24.addLayout(self.horizontalLayout_9)
        self.label_61 = QtWidgets.QLabel(self.groupBox_3)
        self.label_61.setObjectName("label_61")
        self.horizontalLayout_24.addWidget(self.label_61)
        self.lineEdit_p6 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p6.setObjectName("lineEdit_p6")
        self.horizontalLayout_24.addWidget(self.lineEdit_p6)
        self.label_74 = QtWidgets.QLabel(self.groupBox_3)
        self.label_74.setObjectName("label_74")
        self.horizontalLayout_24.addWidget(self.label_74)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.CheckBox_p7 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p7.setText("")
        self.CheckBox_p7.setObjectName("CheckBox_p7")
        self.buttonGroup.addButton(self.CheckBox_p7)
        self.horizontalLayout_10.addWidget(self.CheckBox_p7)
        self.label_49 = QtWidgets.QLabel(self.groupBox_3)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_10.addWidget(self.label_49)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_10)
        self.label_62 = QtWidgets.QLabel(self.groupBox_3)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_25.addWidget(self.label_62)
        self.lineEdit_p7 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p7.setObjectName("lineEdit_p7")
        self.horizontalLayout_25.addWidget(self.lineEdit_p7)
        self.label_75 = QtWidgets.QLabel(self.groupBox_3)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_25.addWidget(self.label_75)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.CheckBox_p8 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p8.setText("")
        self.CheckBox_p8.setObjectName("CheckBox_p8")
        self.buttonGroup.addButton(self.CheckBox_p8)
        self.horizontalLayout_11.addWidget(self.CheckBox_p8)
        self.label_50 = QtWidgets.QLabel(self.groupBox_3)
        self.label_50.setObjectName("label_50")
        self.horizontalLayout_11.addWidget(self.label_50)
        self.horizontalLayout_26.addLayout(self.horizontalLayout_11)
        self.label_63 = QtWidgets.QLabel(self.groupBox_3)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_26.addWidget(self.label_63)
        self.lineEdit_p8 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p8.setObjectName("lineEdit_p8")
        self.horizontalLayout_26.addWidget(self.lineEdit_p8)
        self.label_76 = QtWidgets.QLabel(self.groupBox_3)
        self.label_76.setObjectName("label_76")
        self.horizontalLayout_26.addWidget(self.label_76)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.CheckBox_p9 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p9.setText("")
        self.CheckBox_p9.setObjectName("CheckBox_p9")
        self.buttonGroup.addButton(self.CheckBox_p9)
        self.horizontalLayout_12.addWidget(self.CheckBox_p9)
        self.label_51 = QtWidgets.QLabel(self.groupBox_3)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_12.addWidget(self.label_51)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_12)
        self.label_64 = QtWidgets.QLabel(self.groupBox_3)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_27.addWidget(self.label_64)
        self.lineEdit_p9 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p9.setObjectName("lineEdit_p9")
        self.horizontalLayout_27.addWidget(self.lineEdit_p9)
        self.label_77 = QtWidgets.QLabel(self.groupBox_3)
        self.label_77.setObjectName("label_77")
        self.horizontalLayout_27.addWidget(self.label_77)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.CheckBox_p10 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p10.setText("")
        self.CheckBox_p10.setObjectName("CheckBox_p10")
        self.buttonGroup.addButton(self.CheckBox_p10)
        self.horizontalLayout_13.addWidget(self.CheckBox_p10)
        self.label_52 = QtWidgets.QLabel(self.groupBox_3)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_13.addWidget(self.label_52)
        self.horizontalLayout_28.addLayout(self.horizontalLayout_13)
        self.label_65 = QtWidgets.QLabel(self.groupBox_3)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_28.addWidget(self.label_65)
        self.lineEdit_p10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p10.setObjectName("lineEdit_p10")
        self.horizontalLayout_28.addWidget(self.lineEdit_p10)
        self.label_78 = QtWidgets.QLabel(self.groupBox_3)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_28.addWidget(self.label_78)
        self.verticalLayout.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.CheckBox_p11 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p11.setText("")
        self.CheckBox_p11.setObjectName("CheckBox_p11")
        self.buttonGroup.addButton(self.CheckBox_p11)
        self.horizontalLayout_14.addWidget(self.CheckBox_p11)
        self.label_53 = QtWidgets.QLabel(self.groupBox_3)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_14.addWidget(self.label_53)
        self.horizontalLayout_29.addLayout(self.horizontalLayout_14)
        self.label_66 = QtWidgets.QLabel(self.groupBox_3)
        self.label_66.setObjectName("label_66")
        self.horizontalLayout_29.addWidget(self.label_66)
        self.lineEdit_p11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p11.setObjectName("lineEdit_p11")
        self.horizontalLayout_29.addWidget(self.lineEdit_p11)
        self.label_79 = QtWidgets.QLabel(self.groupBox_3)
        self.label_79.setObjectName("label_79")
        self.horizontalLayout_29.addWidget(self.label_79)
        self.verticalLayout.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.CheckBox_p12 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p12.setText("")
        self.CheckBox_p12.setObjectName("CheckBox_p12")
        self.buttonGroup.addButton(self.CheckBox_p12)
        self.horizontalLayout_15.addWidget(self.CheckBox_p12)
        self.label_54 = QtWidgets.QLabel(self.groupBox_3)
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_15.addWidget(self.label_54)
        self.horizontalLayout_30.addLayout(self.horizontalLayout_15)
        self.label_67 = QtWidgets.QLabel(self.groupBox_3)
        self.label_67.setObjectName("label_67")
        self.horizontalLayout_30.addWidget(self.label_67)
        self.lineEdit_p12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p12.setObjectName("lineEdit_p12")
        self.horizontalLayout_30.addWidget(self.lineEdit_p12)
        self.label_80 = QtWidgets.QLabel(self.groupBox_3)
        self.label_80.setObjectName("label_80")
        self.horizontalLayout_30.addWidget(self.label_80)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.CheckBox_p13 = QtWidgets.QCheckBox(self.groupBox_3)
        self.CheckBox_p13.setText("")
        self.CheckBox_p13.setObjectName("CheckBox_p13")
        self.buttonGroup.addButton(self.CheckBox_p13)
        self.horizontalLayout_16.addWidget(self.CheckBox_p13)
        self.label_55 = QtWidgets.QLabel(self.groupBox_3)
        self.label_55.setObjectName("label_55")
        self.horizontalLayout_16.addWidget(self.label_55)
        self.horizontalLayout_31.addLayout(self.horizontalLayout_16)
        self.label_68 = QtWidgets.QLabel(self.groupBox_3)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_31.addWidget(self.label_68)
        self.lineEdit_p13 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_p13.setObjectName("lineEdit_p13")
        self.horizontalLayout_31.addWidget(self.lineEdit_p13)
        self.label_81 = QtWidgets.QLabel(self.groupBox_3)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_31.addWidget(self.label_81)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_32.addWidget(self.groupBox_3)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_82 = QtWidgets.QLabel(self.groupBox_5)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_17.addWidget(self.label_82)
        self.label_83 = QtWidgets.QLabel(self.groupBox_5)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_17.addWidget(self.label_83)
        self.label_84 = QtWidgets.QLabel(self.groupBox_5)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_17.addWidget(self.label_84)
        self.horizontalLayout_7.addLayout(self.verticalLayout_17)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lineEdit_min = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_min.setObjectName("lineEdit_min")
        self.verticalLayout_18.addWidget(self.lineEdit_min)
        self.lineEdit_step = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_step.setObjectName("lineEdit_step")
        self.verticalLayout_18.addWidget(self.lineEdit_step)
        self.lineEdit_max = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_max.setObjectName("lineEdit_max")
        self.verticalLayout_18.addWidget(self.lineEdit_max)
        self.horizontalLayout_7.addLayout(self.verticalLayout_18)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_85 = QtWidgets.QLabel(self.groupBox_5)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_6.addWidget(self.label_85)
        self.lineEdit_soil_b = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_soil_b.setObjectName("lineEdit_soil_b")
        self.verticalLayout_6.addWidget(self.lineEdit_soil_b)
        self.label_86 = QtWidgets.QLabel(self.groupBox_5)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_6.addWidget(self.label_86)
        self.lineEdit_soil_w = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_soil_w.setObjectName("lineEdit_soil_w")
        self.verticalLayout_6.addWidget(self.lineEdit_soil_w)
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_5.setObjectName("radioButton_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setObjectName("radioButton_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setObjectName("radioButton_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButton_7)
        self.horizontalLayout.addLayout(self.formLayout)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 3, 0, 1, 1)
        self.horizontalLayout_21.addWidget(self.groupBox_5)
        self.mplWidgetSpectral_6 = QMatplotlibWidget(self.groupBox)
        self.mplWidgetSpectral_6.setObjectName("mplWidgetSpectral_6")
        self.horizontalLayout_21.addWidget(self.mplWidgetSpectral_6)
        self.horizontalLayout_32.addLayout(self.horizontalLayout_21)
        self.verticalLayout_3.addLayout(self.horizontalLayout_32)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dialog"))
        self.label.setText(_translate("Form", "PROSAIL Simulation"))
        self.groupBox_6.setTitle(_translate("Form", "I/O"))
        self.label_2.setText(_translate("Form", "Input:"))
        self.pushButton_3.setText(_translate("Form", "Browse"))
        self.label_4.setText(_translate("Form", "Ouput:"))
        self.pushButton_2.setText(_translate("Form", "Save As"))
        self.groupBox_3.setTitle(_translate("Form", "Prosail parameters"))
        self.checkBox.setText(_translate("Form", "Default"))
        self.label_43.setText(_translate("Form", "Structure Parameter(N): [-]                       "))
        self.label_56.setText(_translate("Form", "1.0      "))
        self.lineEdit_p1.setText(_translate("Form", "1.7342"))
        self.label_69.setText(_translate("Form", "3.000"))
        self.label_44.setText(_translate("Form", "Chlorophyll A+ B(Cab): [ug/cm^2]              "))
        self.label_57.setText(_translate("Form", "1.0      "))
        self.lineEdit_p2.setText(_translate("Form", "43.72"))
        self.label_70.setText(_translate("Form", "100.0"))
        self.label_45.setText(_translate("Form", "Water Content (Cw): [cm]                        "))
        self.label_58.setText(_translate("Form", "0.0002"))
        self.lineEdit_p3.setText(_translate("Form", "0.025"))
        self.label_71.setText(_translate("Form", "0.200"))
        self.label_46.setText(_translate("Form", "Dry Matter : [gm/cm^2]                            "))
        self.label_59.setText(_translate("Form", "0.0019"))
        self.lineEdit_p4.setText(_translate("Form", "0.0019"))
        self.label_72.setText(_translate("Form", ".0165"))
        self.label_47.setText(_translate("Form", "Carotenoids (Car):  [ug/cm^2]                 "))
        self.label_60.setText(_translate("Form", "0.0      "))
        self.lineEdit_p5.setText(_translate("Form", "14.91"))
        self.label_73.setText(_translate("Form", "30.00"))
        self.label_48.setText(_translate("Form", "Brown Pigments (Cbrown): [-]                  "))
        self.label_61.setText(_translate("Form", "0.0      "))
        self.lineEdit_p6.setText(_translate("Form", "0.0"))
        self.label_74.setText(_translate("Form", "1.000"))
        self.label_49.setText(_translate("Form", "Anthocyanin (Canth):  [ug/cm^2 ]           "))
        self.label_62.setText(_translate("Form", "0.0      "))
        self.lineEdit_p7.setText(_translate("Form", "0.0"))
        self.label_75.setText(_translate("Form", "10.00"))
        self.label_50.setText(_translate("Form", "Leaf Area Index (LAI):                             "))
        self.label_63.setText(_translate("Form", "0.01    "))
        self.lineEdit_p8.setText(_translate("Form", "4.04"))
        self.label_76.setText(_translate("Form", "10.00"))
        self.label_51.setText(_translate("Form", "Leaf Angle: [deg]                                     "))
        self.label_64.setText(_translate("Form", "0.0      "))
        self.lineEdit_p9.setText(_translate("Form", "45"))
        self.label_77.setText(_translate("Form", "90.00"))
        self.label_52.setText(_translate("Form", "Hot Spot Size Parameter:[-]                    "))
        self.label_65.setText(_translate("Form", "0.0      "))
        self.lineEdit_p10.setText(_translate("Form", "0.37"))
        self.label_78.setText(_translate("Form", "1.000"))
        self.label_53.setText(_translate("Form", "Obs. Zenith Angle: [deg]                        "))
        self.label_66.setText(_translate("Form", "0.0       "))
        self.lineEdit_p11.setText(_translate("Form", "42"))
        self.label_79.setText(_translate("Form", "89.00"))
        self.label_54.setText(_translate("Form", "Sun Zenith Angle: [deg]                          "))
        self.label_67.setText(_translate("Form", "0          "))
        self.lineEdit_p12.setText(_translate("Form", "41"))
        self.label_80.setText(_translate("Form", "89.00"))
        self.label_55.setText(_translate("Form", "Relative Azimuth Angle: [deg]                "))
        self.label_68.setText(_translate("Form", "0          "))
        self.lineEdit_p13.setText(_translate("Form", "110"))
        self.label_81.setText(_translate("Form", "180.0"))
        self.groupBox_5.setTitle(_translate("Form", "Prosail Parameter Sensitivity"))
        self.label_82.setText(_translate("Form", "Minimum"))
        self.label_83.setText(_translate("Form", "Step"))
        self.label_84.setText(_translate("Form", "Maximum"))
        self.label_85.setText(_translate("Form", "Dry Soil Brightness (min=0.0, max=1.00)"))
        self.lineEdit_soil_b.setText(_translate("Form", "0.0"))
        self.label_86.setText(_translate("Form", "Wet Soil Brightness (min=0.0, max=1.00)"))
        self.lineEdit_soil_w.setText(_translate("Form", "0.0"))
        self.groupBox_2.setTitle(_translate("Form", "PROSPECT model"))
        self.radioButton.setText(_translate("Form", "Prospect 5"))
        self.radioButton_2.setText(_translate("Form", "Prospect D"))
        self.groupBox_4.setTitle(_translate("Form", "Reflectance Type"))
        self.radioButton_4.setText(_translate("Form", "SDR"))
        self.radioButton_5.setText(_translate("Form", "BHR"))
        self.radioButton_6.setText(_translate("Form", "DHR"))
        self.radioButton_7.setText(_translate("Form", "HDR"))
        self.pushButton.setText(_translate("Form", "Clear Plot"))

from Ui.qmatplotlibwidget import QMatplotlibWidget
