# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Proximal\proximalAnalysisTool-20220131T051817Z-001\proximalAnalysisTool\Ui\Py6sUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1078, 916)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setTextFormat(QtCore.Qt.RichText)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setWordWrap(False)
        self.label_71.setObjectName("label_71")
        self.horizontalLayout_5.addWidget(self.label_71)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.radioPixel_radiance = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioPixel_radiance.setChecked(True)
        self.radioPixel_radiance.setObjectName("radioPixel_radiance")
        self.buttonGroup_3 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_3.setObjectName("buttonGroup_3")
        self.buttonGroup_3.addButton(self.radioPixel_radiance)
        self.horizontalLayout_22.addWidget(self.radioPixel_radiance)
        self.radioPixel_reflectance = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioPixel_reflectance.setChecked(False)
        self.radioPixel_reflectance.setObjectName("radioPixel_reflectance")
        self.buttonGroup_3.addButton(self.radioPixel_reflectance)
        self.horizontalLayout_22.addWidget(self.radioPixel_reflectance)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_205 = QtWidgets.QLabel(self.groupBox_10)
        self.label_205.setObjectName("label_205")
        self.horizontalLayout_21.addWidget(self.label_205)
        self.x1CoordEdit_272 = QtWidgets.QLineEdit(self.groupBox_10)
        self.x1CoordEdit_272.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_272.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_272.setSizePolicy(sizePolicy)
        self.x1CoordEdit_272.setObjectName("x1CoordEdit_272")
        self.horizontalLayout_21.addWidget(self.x1CoordEdit_272)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_206 = QtWidgets.QLabel(self.groupBox_10)
        self.label_206.setObjectName("label_206")
        self.horizontalLayout_31.addWidget(self.label_206)
        self.x1CoordEdit_273 = QtWidgets.QLineEdit(self.groupBox_10)
        self.x1CoordEdit_273.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_273.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_273.setSizePolicy(sizePolicy)
        self.x1CoordEdit_273.setObjectName("x1CoordEdit_273")
        self.horizontalLayout_31.addWidget(self.x1CoordEdit_273)
        self.verticalLayout_3.addLayout(self.horizontalLayout_31)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.label_207 = QtWidgets.QLabel(self.groupBox_10)
        self.label_207.setObjectName("label_207")
        self.horizontalLayout_33.addWidget(self.label_207)
        self.x1CoordEdit_274 = QtWidgets.QLineEdit(self.groupBox_10)
        self.x1CoordEdit_274.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_274.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_274.setSizePolicy(sizePolicy)
        self.x1CoordEdit_274.setObjectName("x1CoordEdit_274")
        self.horizontalLayout_33.addWidget(self.x1CoordEdit_274)
        self.verticalLayout_3.addLayout(self.horizontalLayout_33)
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_208 = QtWidgets.QLabel(self.groupBox_10)
        self.label_208.setObjectName("label_208")
        self.horizontalLayout_34.addWidget(self.label_208)
        self.x1CoordEdit_275 = QtWidgets.QLineEdit(self.groupBox_10)
        self.x1CoordEdit_275.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_275.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_275.setSizePolicy(sizePolicy)
        self.x1CoordEdit_275.setObjectName("x1CoordEdit_275")
        self.horizontalLayout_34.addWidget(self.x1CoordEdit_275)
        self.verticalLayout_3.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_209 = QtWidgets.QLabel(self.groupBox_10)
        self.label_209.setObjectName("label_209")
        self.horizontalLayout_35.addWidget(self.label_209)
        self.x1CoordEdit_276 = QtWidgets.QLineEdit(self.groupBox_10)
        self.x1CoordEdit_276.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_276.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_276.setSizePolicy(sizePolicy)
        self.x1CoordEdit_276.setObjectName("x1CoordEdit_276")
        self.horizontalLayout_35.addWidget(self.x1CoordEdit_276)
        self.verticalLayout_3.addLayout(self.horizontalLayout_35)
        self.verticalLayout_5.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.checkBox_29 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_29.setObjectName("checkBox_29")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.checkBox_29)
        self.gridLayout_19.addWidget(self.checkBox_29, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_195 = QtWidgets.QLabel(self.groupBox_11)
        self.label_195.setObjectName("label_195")
        self.horizontalLayout_23.addWidget(self.label_195)
        self.x1CoordEdit_262 = QtWidgets.QLineEdit(self.groupBox_11)
        self.x1CoordEdit_262.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_262.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_262.setSizePolicy(sizePolicy)
        self.x1CoordEdit_262.setObjectName("x1CoordEdit_262")
        self.horizontalLayout_23.addWidget(self.x1CoordEdit_262)
        self.gridLayout_19.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_196 = QtWidgets.QLabel(self.groupBox_11)
        self.label_196.setObjectName("label_196")
        self.horizontalLayout_24.addWidget(self.label_196)
        self.x1CoordEdit_263 = QtWidgets.QLineEdit(self.groupBox_11)
        self.x1CoordEdit_263.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_263.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_263.setSizePolicy(sizePolicy)
        self.x1CoordEdit_263.setObjectName("x1CoordEdit_263")
        self.horizontalLayout_24.addWidget(self.x1CoordEdit_263)
        self.gridLayout_19.addLayout(self.horizontalLayout_24, 2, 0, 1, 1)
        self.gridLayout_20 = QtWidgets.QGridLayout()
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.checkBox_30 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_30.setChecked(True)
        self.checkBox_30.setObjectName("checkBox_30")
        self.buttonGroup_2.addButton(self.checkBox_30)
        self.gridLayout_20.addWidget(self.checkBox_30, 0, 0, 1, 1)
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_31.setObjectName("checkBox_31")
        self.buttonGroup_2.addButton(self.checkBox_31)
        self.gridLayout_20.addWidget(self.checkBox_31, 0, 1, 1, 1)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_32.setObjectName("checkBox_32")
        self.buttonGroup_2.addButton(self.checkBox_32)
        self.gridLayout_20.addWidget(self.checkBox_32, 1, 0, 1, 1)
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_33.setObjectName("checkBox_33")
        self.buttonGroup_2.addButton(self.checkBox_33)
        self.gridLayout_20.addWidget(self.checkBox_33, 1, 1, 1, 1)
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_34.setObjectName("checkBox_34")
        self.buttonGroup_2.addButton(self.checkBox_34)
        self.gridLayout_20.addWidget(self.checkBox_34, 2, 0, 1, 1)
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox_11)
        self.checkBox_35.setObjectName("checkBox_35")
        self.buttonGroup_2.addButton(self.checkBox_35)
        self.gridLayout_20.addWidget(self.checkBox_35, 2, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_20, 3, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_12.setObjectName("groupBox_12")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.groupBox_12)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.checkBox_36 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_36.setChecked(True)
        self.checkBox_36.setObjectName("checkBox_36")
        self.buttonGroup_6 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_6.setObjectName("buttonGroup_6")
        self.buttonGroup_6.addButton(self.checkBox_36)
        self.gridLayout_22.addWidget(self.checkBox_36, 0, 0, 1, 1)
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_37.setObjectName("checkBox_37")
        self.buttonGroup_6.addButton(self.checkBox_37)
        self.gridLayout_22.addWidget(self.checkBox_37, 0, 1, 1, 1)
        self.checkBox_38 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_38.setObjectName("checkBox_38")
        self.buttonGroup_6.addButton(self.checkBox_38)
        self.gridLayout_22.addWidget(self.checkBox_38, 1, 0, 1, 1)
        self.checkBox_39 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_39.setObjectName("checkBox_39")
        self.buttonGroup_6.addButton(self.checkBox_39)
        self.gridLayout_22.addWidget(self.checkBox_39, 1, 1, 1, 1)
        self.checkBox_40 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_40.setObjectName("checkBox_40")
        self.buttonGroup_6.addButton(self.checkBox_40)
        self.gridLayout_22.addWidget(self.checkBox_40, 2, 0, 1, 1)
        self.checkBox_41 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_41.setObjectName("checkBox_41")
        self.buttonGroup_6.addButton(self.checkBox_41)
        self.gridLayout_22.addWidget(self.checkBox_41, 2, 1, 1, 1)
        self.checkBox_42 = QtWidgets.QCheckBox(self.groupBox_12)
        self.checkBox_42.setObjectName("checkBox_42")
        self.buttonGroup_6.addButton(self.checkBox_42)
        self.gridLayout_22.addWidget(self.checkBox_42, 3, 0, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_22, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_197 = QtWidgets.QLabel(self.groupBox_13)
        self.label_197.setObjectName("label_197")
        self.horizontalLayout_25.addWidget(self.label_197)
        self.x1CoordEdit_264 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_264.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_264.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_264.setSizePolicy(sizePolicy)
        self.x1CoordEdit_264.setObjectName("x1CoordEdit_264")
        self.horizontalLayout_25.addWidget(self.x1CoordEdit_264)
        self.verticalLayout_8.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_198 = QtWidgets.QLabel(self.groupBox_13)
        self.label_198.setObjectName("label_198")
        self.horizontalLayout_26.addWidget(self.label_198)
        self.x1CoordEdit_265 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_265.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_265.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_265.setSizePolicy(sizePolicy)
        self.x1CoordEdit_265.setObjectName("x1CoordEdit_265")
        self.horizontalLayout_26.addWidget(self.x1CoordEdit_265)
        self.verticalLayout_8.addLayout(self.horizontalLayout_26)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_199 = QtWidgets.QLabel(self.groupBox_13)
        self.label_199.setObjectName("label_199")
        self.horizontalLayout_27.addWidget(self.label_199)
        self.x1CoordEdit_266 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_266.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_266.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_266.setSizePolicy(sizePolicy)
        self.x1CoordEdit_266.setObjectName("x1CoordEdit_266")
        self.horizontalLayout_27.addWidget(self.x1CoordEdit_266)
        self.verticalLayout_8.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_200 = QtWidgets.QLabel(self.groupBox_13)
        self.label_200.setObjectName("label_200")
        self.horizontalLayout_28.addWidget(self.label_200)
        self.x1CoordEdit_267 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_267.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_267.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_267.setSizePolicy(sizePolicy)
        self.x1CoordEdit_267.setObjectName("x1CoordEdit_267")
        self.horizontalLayout_28.addWidget(self.x1CoordEdit_267)
        self.verticalLayout_8.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_201 = QtWidgets.QLabel(self.groupBox_13)
        self.label_201.setObjectName("label_201")
        self.horizontalLayout_29.addWidget(self.label_201)
        self.x1CoordEdit_268 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_268.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_268.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_268.setSizePolicy(sizePolicy)
        self.x1CoordEdit_268.setObjectName("x1CoordEdit_268")
        self.horizontalLayout_29.addWidget(self.x1CoordEdit_268)
        self.verticalLayout_8.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_202 = QtWidgets.QLabel(self.groupBox_13)
        self.label_202.setObjectName("label_202")
        self.horizontalLayout_30.addWidget(self.label_202)
        self.x1CoordEdit_269 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_269.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_269.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_269.setSizePolicy(sizePolicy)
        self.x1CoordEdit_269.setObjectName("x1CoordEdit_269")
        self.horizontalLayout_30.addWidget(self.x1CoordEdit_269)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_203 = QtWidgets.QLabel(self.groupBox_13)
        self.label_203.setObjectName("label_203")
        self.gridLayout_23.addWidget(self.label_203, 0, 0, 1, 1)
        self.x1CoordEdit_270 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_270.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_270.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_270.setSizePolicy(sizePolicy)
        self.x1CoordEdit_270.setObjectName("x1CoordEdit_270")
        self.gridLayout_23.addWidget(self.x1CoordEdit_270, 0, 1, 1, 1)
        self.label_204 = QtWidgets.QLabel(self.groupBox_13)
        self.label_204.setObjectName("label_204")
        self.gridLayout_23.addWidget(self.label_204, 1, 0, 1, 1)
        self.x1CoordEdit_271 = QtWidgets.QLineEdit(self.groupBox_13)
        self.x1CoordEdit_271.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_271.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_271.setSizePolicy(sizePolicy)
        self.x1CoordEdit_271.setObjectName("x1CoordEdit_271")
        self.gridLayout_23.addWidget(self.x1CoordEdit_271, 1, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_23)
        self.verticalLayout_5.addWidget(self.groupBox_13)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_5, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout = QtWidgets.QGridLayout(self.tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_select = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_select.setEnabled(True)
        self.checkBox_select.setObjectName("checkBox_select")
        self.verticalLayout.addWidget(self.checkBox_select)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox_14)
        self.label_70.setObjectName("label_70")
        self.horizontalLayout.addWidget(self.label_70)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_5.setEnabled(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_73 = QtWidgets.QLabel(self.groupBox_14)
        self.label_73.setObjectName("label_73")
        self.horizontalLayout_2.addWidget(self.label_73)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_6.setEnabled(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_5.setEnabled(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_72 = QtWidgets.QLabel(self.groupBox_14)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_3.addWidget(self.label_72)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_3.addWidget(self.lineEdit_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_14)
        self.pushButton_6.setEnabled(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_3.addWidget(self.pushButton_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox_14)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_19 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.radioPixel_radiance_3 = QtWidgets.QRadioButton(self.groupBox_19)
        self.radioPixel_radiance_3.setChecked(True)
        self.radioPixel_radiance_3.setObjectName("radioPixel_radiance_3")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioPixel_radiance_3)
        self.horizontalLayout_32.addWidget(self.radioPixel_radiance_3)
        self.radioPixel_reflectance_3 = QtWidgets.QRadioButton(self.groupBox_19)
        self.radioPixel_reflectance_3.setChecked(False)
        self.radioPixel_reflectance_3.setObjectName("radioPixel_reflectance_3")
        self.buttonGroup.addButton(self.radioPixel_reflectance_3)
        self.horizontalLayout_32.addWidget(self.radioPixel_reflectance_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.label_226 = QtWidgets.QLabel(self.groupBox_19)
        self.label_226.setObjectName("label_226")
        self.horizontalLayout_51.addWidget(self.label_226)
        self.x1CoordEdit_293 = QtWidgets.QLineEdit(self.groupBox_19)
        self.x1CoordEdit_293.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_293.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_293.setSizePolicy(sizePolicy)
        self.x1CoordEdit_293.setObjectName("x1CoordEdit_293")
        self.horizontalLayout_51.addWidget(self.x1CoordEdit_293)
        self.verticalLayout_2.addLayout(self.horizontalLayout_51)
        self.verticalLayout_4.addWidget(self.groupBox_19)
        self.groupBox_20 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.checkBox_57 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_57.setObjectName("checkBox_57")
        self.buttonGroup_4 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_4.setObjectName("buttonGroup_4")
        self.buttonGroup_4.addButton(self.checkBox_57)
        self.gridLayout_29.addWidget(self.checkBox_57, 0, 0, 1, 1)
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.label_230 = QtWidgets.QLabel(self.groupBox_20)
        self.label_230.setObjectName("label_230")
        self.horizontalLayout_55.addWidget(self.label_230)
        self.x1CoordEdit_297 = QtWidgets.QLineEdit(self.groupBox_20)
        self.x1CoordEdit_297.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_297.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_297.setSizePolicy(sizePolicy)
        self.x1CoordEdit_297.setObjectName("x1CoordEdit_297")
        self.horizontalLayout_55.addWidget(self.x1CoordEdit_297)
        self.gridLayout_29.addLayout(self.horizontalLayout_55, 1, 0, 1, 1)
        self.horizontalLayout_56 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_56.setObjectName("horizontalLayout_56")
        self.label_231 = QtWidgets.QLabel(self.groupBox_20)
        self.label_231.setObjectName("label_231")
        self.horizontalLayout_56.addWidget(self.label_231)
        self.x1CoordEdit_298 = QtWidgets.QLineEdit(self.groupBox_20)
        self.x1CoordEdit_298.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_298.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_298.setSizePolicy(sizePolicy)
        self.x1CoordEdit_298.setObjectName("x1CoordEdit_298")
        self.horizontalLayout_56.addWidget(self.x1CoordEdit_298)
        self.gridLayout_29.addLayout(self.horizontalLayout_56, 2, 0, 1, 1)
        self.gridLayout_30 = QtWidgets.QGridLayout()
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.checkBox_58 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_58.setChecked(True)
        self.checkBox_58.setObjectName("checkBox_58")
        self.buttonGroup_4.addButton(self.checkBox_58)
        self.gridLayout_30.addWidget(self.checkBox_58, 0, 0, 1, 1)
        self.checkBox_59 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_59.setObjectName("checkBox_59")
        self.buttonGroup_4.addButton(self.checkBox_59)
        self.gridLayout_30.addWidget(self.checkBox_59, 0, 1, 1, 1)
        self.checkBox_60 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_60.setObjectName("checkBox_60")
        self.buttonGroup_4.addButton(self.checkBox_60)
        self.gridLayout_30.addWidget(self.checkBox_60, 1, 0, 1, 1)
        self.checkBox_61 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_61.setObjectName("checkBox_61")
        self.buttonGroup_4.addButton(self.checkBox_61)
        self.gridLayout_30.addWidget(self.checkBox_61, 1, 1, 1, 1)
        self.checkBox_62 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_62.setObjectName("checkBox_62")
        self.buttonGroup_4.addButton(self.checkBox_62)
        self.gridLayout_30.addWidget(self.checkBox_62, 2, 0, 1, 1)
        self.checkBox_63 = QtWidgets.QCheckBox(self.groupBox_20)
        self.checkBox_63.setObjectName("checkBox_63")
        self.buttonGroup_4.addButton(self.checkBox_63)
        self.gridLayout_30.addWidget(self.checkBox_63, 2, 1, 1, 1)
        self.gridLayout_29.addLayout(self.gridLayout_30, 3, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_20)
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_21.setObjectName("groupBox_21")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.groupBox_21)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_32 = QtWidgets.QGridLayout()
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.checkBox_64 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_64.setChecked(True)
        self.checkBox_64.setObjectName("checkBox_64")
        self.buttonGroup_5 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_5.setObjectName("buttonGroup_5")
        self.buttonGroup_5.addButton(self.checkBox_64)
        self.gridLayout_32.addWidget(self.checkBox_64, 0, 0, 1, 1)
        self.checkBox_65 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_65.setObjectName("checkBox_65")
        self.buttonGroup_5.addButton(self.checkBox_65)
        self.gridLayout_32.addWidget(self.checkBox_65, 0, 1, 1, 1)
        self.checkBox_66 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_66.setObjectName("checkBox_66")
        self.buttonGroup_5.addButton(self.checkBox_66)
        self.gridLayout_32.addWidget(self.checkBox_66, 1, 0, 1, 1)
        self.checkBox_67 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_67.setObjectName("checkBox_67")
        self.buttonGroup_5.addButton(self.checkBox_67)
        self.gridLayout_32.addWidget(self.checkBox_67, 1, 1, 1, 1)
        self.checkBox_68 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_68.setObjectName("checkBox_68")
        self.buttonGroup_5.addButton(self.checkBox_68)
        self.gridLayout_32.addWidget(self.checkBox_68, 2, 0, 1, 1)
        self.checkBox_69 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_69.setObjectName("checkBox_69")
        self.buttonGroup_5.addButton(self.checkBox_69)
        self.gridLayout_32.addWidget(self.checkBox_69, 2, 1, 1, 1)
        self.checkBox_70 = QtWidgets.QCheckBox(self.groupBox_21)
        self.checkBox_70.setObjectName("checkBox_70")
        self.buttonGroup_5.addButton(self.checkBox_70)
        self.gridLayout_32.addWidget(self.checkBox_70, 3, 0, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_32, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_21)
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_22.setObjectName("groupBox_22")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_232 = QtWidgets.QLabel(self.groupBox_22)
        self.label_232.setObjectName("label_232")
        self.horizontalLayout_57.addWidget(self.label_232)
        self.x1CoordEdit_299 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_299.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_299.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_299.setSizePolicy(sizePolicy)
        self.x1CoordEdit_299.setObjectName("x1CoordEdit_299")
        self.horizontalLayout_57.addWidget(self.x1CoordEdit_299)
        self.verticalLayout_11.addLayout(self.horizontalLayout_57)
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.label_233 = QtWidgets.QLabel(self.groupBox_22)
        self.label_233.setObjectName("label_233")
        self.horizontalLayout_58.addWidget(self.label_233)
        self.x1CoordEdit_300 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_300.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_300.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_300.setSizePolicy(sizePolicy)
        self.x1CoordEdit_300.setObjectName("x1CoordEdit_300")
        self.horizontalLayout_58.addWidget(self.x1CoordEdit_300)
        self.verticalLayout_11.addLayout(self.horizontalLayout_58)
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_234 = QtWidgets.QLabel(self.groupBox_22)
        self.label_234.setObjectName("label_234")
        self.horizontalLayout_59.addWidget(self.label_234)
        self.x1CoordEdit_301 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_301.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_301.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_301.setSizePolicy(sizePolicy)
        self.x1CoordEdit_301.setObjectName("x1CoordEdit_301")
        self.horizontalLayout_59.addWidget(self.x1CoordEdit_301)
        self.verticalLayout_11.addLayout(self.horizontalLayout_59)
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.label_235 = QtWidgets.QLabel(self.groupBox_22)
        self.label_235.setObjectName("label_235")
        self.horizontalLayout_60.addWidget(self.label_235)
        self.x1CoordEdit_302 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_302.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_302.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_302.setSizePolicy(sizePolicy)
        self.x1CoordEdit_302.setObjectName("x1CoordEdit_302")
        self.horizontalLayout_60.addWidget(self.x1CoordEdit_302)
        self.verticalLayout_11.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_236 = QtWidgets.QLabel(self.groupBox_22)
        self.label_236.setObjectName("label_236")
        self.horizontalLayout_61.addWidget(self.label_236)
        self.x1CoordEdit_303 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_303.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_303.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_303.setSizePolicy(sizePolicy)
        self.x1CoordEdit_303.setObjectName("x1CoordEdit_303")
        self.horizontalLayout_61.addWidget(self.x1CoordEdit_303)
        self.verticalLayout_11.addLayout(self.horizontalLayout_61)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.label_237 = QtWidgets.QLabel(self.groupBox_22)
        self.label_237.setObjectName("label_237")
        self.horizontalLayout_62.addWidget(self.label_237)
        self.x1CoordEdit_304 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_304.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_304.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_304.setSizePolicy(sizePolicy)
        self.x1CoordEdit_304.setObjectName("x1CoordEdit_304")
        self.horizontalLayout_62.addWidget(self.x1CoordEdit_304)
        self.verticalLayout_11.addLayout(self.horizontalLayout_62)
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.label_238 = QtWidgets.QLabel(self.groupBox_22)
        self.label_238.setObjectName("label_238")
        self.gridLayout_33.addWidget(self.label_238, 0, 0, 1, 1)
        self.x1CoordEdit_305 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_305.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_305.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_305.setSizePolicy(sizePolicy)
        self.x1CoordEdit_305.setObjectName("x1CoordEdit_305")
        self.gridLayout_33.addWidget(self.x1CoordEdit_305, 0, 1, 1, 1)
        self.label_239 = QtWidgets.QLabel(self.groupBox_22)
        self.label_239.setObjectName("label_239")
        self.gridLayout_33.addWidget(self.label_239, 1, 0, 1, 1)
        self.x1CoordEdit_306 = QtWidgets.QLineEdit(self.groupBox_22)
        self.x1CoordEdit_306.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_306.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_306.setSizePolicy(sizePolicy)
        self.x1CoordEdit_306.setObjectName("x1CoordEdit_306")
        self.gridLayout_33.addWidget(self.x1CoordEdit_306, 1, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_33)
        self.verticalLayout_4.addWidget(self.groupBox_22)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.mplWidgetSpectral_15 = QMatplotlibWidget(self.tab)
        self.mplWidgetSpectral_15.setObjectName("mplWidgetSpectral_15")
        self.horizontalLayout_4.addWidget(self.mplWidgetSpectral_15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab, "")
        self.verticalLayout_7.addWidget(self.tabWidget_4)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Timeseries Analysis"))
        self.label_71.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Py6S Simulations</span></p></body></html>"))
        self.groupBox_10.setTitle(_translate("Form", "Type of O/P values [Homogenous Lambertian Model]"))
        self.radioPixel_radiance.setText(_translate("Form", "Pixel Radiance"))
        self.radioPixel_reflectance.setText(_translate("Form", "Pixel Reflectance"))
        self.label_205.setText(_translate("Form", "Select Wavelength (micrometer)"))
        self.x1CoordEdit_272.setText(_translate("Form", "0.700"))
        self.label_206.setText(_translate("Form", "Albedo  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_273.setText(_translate("Form", "0.5"))
        self.label_207.setText(_translate("Form", "param1 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_274.setText(_translate("Form", "0.48"))
        self.label_208.setText(_translate("Form", "param2 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_275.setText(_translate("Form", "0.50"))
        self.label_209.setText(_translate("Form", "param3 -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_276.setText(_translate("Form", "2.95"))
        self.groupBox_11.setTitle(_translate("Form", "Atmospheric Profile"))
        self.checkBox_29.setText(_translate("Form", "User Defined"))
        self.label_195.setText(_translate("Form", "Water ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_262.setText(_translate("Form", "3.6"))
        self.label_196.setText(_translate("Form", "Ozone -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_263.setText(_translate("Form", "0.9"))
        self.checkBox_30.setText(_translate("Form", "NoGaseousAbsorption"))
        self.checkBox_31.setText(_translate("Form", "Tropical "))
        self.checkBox_32.setText(_translate("Form", "MidlatitudeSummer "))
        self.checkBox_33.setText(_translate("Form", "MidlatitudeWinter "))
        self.checkBox_34.setText(_translate("Form", "SubarcticSummer "))
        self.checkBox_35.setText(_translate("Form", "SubarcticWinter "))
        self.groupBox_12.setTitle(_translate("Form", "Aerosol Profile"))
        self.checkBox_36.setText(_translate("Form", "NoAerosols "))
        self.checkBox_37.setText(_translate("Form", "Continental "))
        self.checkBox_38.setText(_translate("Form", "Maritime "))
        self.checkBox_39.setText(_translate("Form", "Urban "))
        self.checkBox_40.setText(_translate("Form", "Desert "))
        self.checkBox_41.setText(_translate("Form", "BiomassBurning "))
        self.checkBox_42.setText(_translate("Form", "Stratospheric "))
        self.groupBox_13.setTitle(_translate("Form", "Geometry"))
        self.label_197.setText(_translate("Form", "Solar Zenith Angle -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_264.setText(_translate("Form", "45"))
        self.label_198.setText(_translate("Form", "Solar Azimuth Angle --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_265.setText(_translate("Form", "41"))
        self.label_199.setText(_translate("Form", "View Zenith Angle   -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_266.setText(_translate("Form", "40"))
        self.label_200.setText(_translate("Form", "View Azimuth Angle  ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_267.setText(_translate("Form", "50"))
        self.label_201.setText(_translate("Form", "Month   -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_268.setText(_translate("Form", "5"))
        self.label_202.setText(_translate("Form", "Day     -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_269.setText(_translate("Form", "30"))
        self.label_203.setText(_translate("Form", "Sensor Altitude (km)  -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_270.setText(_translate("Form", "700"))
        self.label_204.setText(_translate("Form", "Target Altitude (from Sea level) (km)   ----------------------------------------------------------------------------------------------------------------------------------------------------------------"))
        self.x1CoordEdit_271.setText(_translate("Form", "0.1"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_5), _translate("Form", "Py6S Angular Simulation"))
        self.groupBox_14.setTitle(_translate("Form", "I/O"))
        self.checkBox_select.setText(_translate("Form", "Activate to input user specific spectrum"))
        self.label_70.setText(_translate("Form", "Target Spectrum (*.csv)"))
        self.pushButton_4.setText(_translate("Form", "Browse"))
        self.label_73.setText(_translate("Form", "Background Spectra (*.csv)"))
        self.pushButton_5.setText(_translate("Form", "Browse"))
        self.label_72.setText(_translate("Form", "Output Spectrum (*.csv)"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.groupBox_19.setTitle(_translate("Form", "Type of O/P values [Walthall Model]"))
        self.radioPixel_radiance_3.setText(_translate("Form", "Pixel Radiance"))
        self.radioPixel_reflectance_3.setText(_translate("Form", "Pixel Reflectance"))
        self.label_226.setText(_translate("Form", "Radius (km)"))
        self.x1CoordEdit_293.setText(_translate("Form", "0.5"))
        self.groupBox_20.setTitle(_translate("Form", "Atmospheric Profile"))
        self.checkBox_57.setText(_translate("Form", "User Defined"))
        self.label_230.setText(_translate("Form", "Water"))
        self.x1CoordEdit_297.setText(_translate("Form", "3.6"))
        self.label_231.setText(_translate("Form", "Ozone"))
        self.x1CoordEdit_298.setText(_translate("Form", "0.9"))
        self.checkBox_58.setText(_translate("Form", "NoGaseousAbsorption"))
        self.checkBox_59.setText(_translate("Form", "Tropical "))
        self.checkBox_60.setText(_translate("Form", "MidlatitudeSummer "))
        self.checkBox_61.setText(_translate("Form", "MidlatitudeWinter "))
        self.checkBox_62.setText(_translate("Form", "SubarcticSummer "))
        self.checkBox_63.setText(_translate("Form", "SubarcticWinter "))
        self.groupBox_21.setTitle(_translate("Form", "Aerosol Profile"))
        self.checkBox_64.setText(_translate("Form", "NoAerosols "))
        self.checkBox_65.setText(_translate("Form", "Continental "))
        self.checkBox_66.setText(_translate("Form", "Maritime "))
        self.checkBox_67.setText(_translate("Form", "Urban "))
        self.checkBox_68.setText(_translate("Form", "Desert "))
        self.checkBox_69.setText(_translate("Form", "BiomassBurning "))
        self.checkBox_70.setText(_translate("Form", "Stratospheric "))
        self.groupBox_22.setTitle(_translate("Form", "Geometry"))
        self.label_232.setText(_translate("Form", "Solar Zenith Angle"))
        self.x1CoordEdit_299.setText(_translate("Form", "45"))
        self.label_233.setText(_translate("Form", "Solar Azimuth Angle"))
        self.x1CoordEdit_300.setText(_translate("Form", "41"))
        self.label_234.setText(_translate("Form", "View Zenith Angle"))
        self.x1CoordEdit_301.setText(_translate("Form", "40"))
        self.label_235.setText(_translate("Form", "View Azimuth Angle"))
        self.x1CoordEdit_302.setText(_translate("Form", "50"))
        self.label_236.setText(_translate("Form", "Month"))
        self.x1CoordEdit_303.setText(_translate("Form", "5"))
        self.label_237.setText(_translate("Form", "Day"))
        self.x1CoordEdit_304.setText(_translate("Form", "30"))
        self.label_238.setText(_translate("Form", "Sensor Altitude (km)"))
        self.x1CoordEdit_305.setText(_translate("Form", "700"))
        self.label_239.setText(_translate("Form", "Target Altitude (from Sea level) (km)"))
        self.x1CoordEdit_306.setText(_translate("Form", "0.1"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab), _translate("Form", "Py6S with User Input sepctra"))

from Ui.qmatplotlibwidget import QMatplotlibWidget
