# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Proximal\ProximalAnalysisTool\Ui\Spectra_simulation_SACUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1069, 596)
        self.gridLayout_5 = QtWidgets.QGridLayout(Form)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_29)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_29)
        self.groupBox_34.setTitle("")
        self.groupBox_34.setObjectName("groupBox_34")
        self.verticalLayout_80 = QtWidgets.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.Linear_mixing_button = QtWidgets.QRadioButton(self.groupBox_34)
        self.Linear_mixing_button.setChecked(True)
        self.Linear_mixing_button.setObjectName("Linear_mixing_button")
        self.verticalLayout_80.addWidget(self.Linear_mixing_button)
        self.label_73 = QtWidgets.QLabel(self.groupBox_34)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_80.addWidget(self.label_73)
        self.x1CoordEdit_11 = QtWidgets.QLineEdit(self.groupBox_34)
        self.x1CoordEdit_11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_11.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_11.setSizePolicy(sizePolicy)
        self.x1CoordEdit_11.setObjectName("x1CoordEdit_11")
        self.verticalLayout_80.addWidget(self.x1CoordEdit_11)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.verticalLayout_80.addLayout(self.horizontalLayout_62)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_34)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_80.addWidget(self.radioButton)
        self.label = QtWidgets.QLabel(self.groupBox_34)
        self.label.setObjectName("label")
        self.verticalLayout_80.addWidget(self.label)
        self.x1CoordEdit_12 = QtWidgets.QLineEdit(self.groupBox_34)
        self.x1CoordEdit_12.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_12.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_12.setSizePolicy(sizePolicy)
        self.x1CoordEdit_12.setObjectName("x1CoordEdit_12")
        self.verticalLayout_80.addWidget(self.x1CoordEdit_12)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_34)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_80.addWidget(self.radioButton_2)
        self.label_74 = QtWidgets.QLabel(self.groupBox_34)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_80.addWidget(self.label_74)
        self.x1CoordEdit_13 = QtWidgets.QLineEdit(self.groupBox_34)
        self.x1CoordEdit_13.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_13.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_13.setSizePolicy(sizePolicy)
        self.x1CoordEdit_13.setObjectName("x1CoordEdit_13")
        self.verticalLayout_80.addWidget(self.x1CoordEdit_13)
        self.label_2 = QtWidgets.QLabel(self.groupBox_34)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_80.addWidget(self.label_2)
        self.x1CoordEdit_14 = QtWidgets.QLineEdit(self.groupBox_34)
        self.x1CoordEdit_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_14.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_14.setSizePolicy(sizePolicy)
        self.x1CoordEdit_14.setObjectName("x1CoordEdit_14")
        self.verticalLayout_80.addWidget(self.x1CoordEdit_14)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_34)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_80.addWidget(self.pushButton)
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.verticalLayout_80.addLayout(self.horizontalLayout_63)
        self.verticalLayout_79.addWidget(self.groupBox_34)
        spacerItem = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_79.addItem(spacerItem)
        self.horizontalLayout_61.addLayout(self.verticalLayout_79)
        self.mplWidgetSpectral_5 = QMatplotlibWidget(self.tab_29)
        self.mplWidgetSpectral_5.setObjectName("mplWidgetSpectral_5")
        self.horizontalLayout_61.addWidget(self.mplWidgetSpectral_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_61, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_29, "")
        self.gridLayout.addWidget(self.tabWidget_4, 2, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Timeseries Analysis"))
        self.groupBox.setTitle(_translate("Form", "Spectra Simulation"))
        self.label_70.setText(_translate("Form", "Spectra (*.csv) "))
        self.pushButton_4.setText(_translate("Form", "Browse"))
        self.label_72.setText(_translate("Form", "Output"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.Linear_mixing_button.setText(_translate("Form", "Linear Mixing"))
        self.label_73.setText(_translate("Form", "Fraction range=[0-1]"))
        self.x1CoordEdit_11.setText(_translate("Form", "0.5"))
        self.radioButton.setText(_translate("Form", "Bi-linear Generalized Mixing"))
        self.label.setText(_translate("Form", "Constant range=[0-1]"))
        self.x1CoordEdit_12.setText(_translate("Form", "0.5"))
        self.radioButton_2.setText(_translate("Form", "Fans "))
        self.label_74.setText(_translate("Form", "Fraction range=[0-1]"))
        self.x1CoordEdit_13.setText(_translate("Form", "0.5"))
        self.label_2.setText(_translate("Form", "Constant range=[0-1]"))
        self.x1CoordEdit_14.setText(_translate("Form", "0.5"))
        self.pushButton.setText(_translate("Form", "Clear plot"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_29), _translate("Form", "Spectra Simulation "))

from Ui.qmatplotlibwidget import QMatplotlibWidget
