# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Proximal\proximalAnalysisTool-20220131T051817Z-001\proximalAnalysisTool\Ui\SpectralPre_TransformUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 518)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 1, 0, 1, 1)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.gridLayout_57 = QtWidgets.QGridLayout(self.tab_29)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_29)
        self.groupBox_34.setObjectName("groupBox_34")
        self.verticalLayout_80 = QtWidgets.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.Soil_property = QtWidgets.QRadioButton(self.groupBox_34)
        self.Soil_property.setChecked(True)
        self.Soil_property.setObjectName("Soil_property")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.Soil_property)
        self.verticalLayout_80.addWidget(self.Soil_property)
        self.Transform_box_cox = QtWidgets.QRadioButton(self.groupBox_34)
        self.Transform_box_cox.setChecked(False)
        self.Transform_box_cox.setObjectName("Transform_box_cox")
        self.buttonGroup_2.addButton(self.Transform_box_cox)
        self.verticalLayout_80.addWidget(self.Transform_box_cox)
        self.Transform_log = QtWidgets.QRadioButton(self.groupBox_34)
        self.Transform_log.setObjectName("Transform_log")
        self.buttonGroup_2.addButton(self.Transform_log)
        self.verticalLayout_80.addWidget(self.Transform_log)
        self.Transform_standard = QtWidgets.QRadioButton(self.groupBox_34)
        self.Transform_standard.setObjectName("Transform_standard")
        self.buttonGroup_2.addButton(self.Transform_standard)
        self.verticalLayout_80.addWidget(self.Transform_standard)
        self.Plot_spectra = QtWidgets.QRadioButton(self.groupBox_34)
        self.Plot_spectra.setObjectName("Plot_spectra")
        self.buttonGroup_2.addButton(self.Plot_spectra)
        self.verticalLayout_80.addWidget(self.Plot_spectra)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.verticalLayout_80.addLayout(self.horizontalLayout_62)
        self.verticalLayout_79.addWidget(self.groupBox_34)
        spacerItem = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_79.addItem(spacerItem)
        self.horizontalLayout_61.addLayout(self.verticalLayout_79)
        self.mplWidgetSpectral_5 = QMatplotlibWidget(self.tab_29)
        self.mplWidgetSpectral_5.setObjectName("mplWidgetSpectral_5")
        self.horizontalLayout_61.addWidget(self.mplWidgetSpectral_5)
        self.gridLayout_57.addLayout(self.horizontalLayout_61, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_29, "")
        self.tab_44 = QtWidgets.QWidget()
        self.tab_44.setObjectName("tab_44")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_44)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.verticalLayout_81 = QtWidgets.QVBoxLayout()
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_44)
        self.groupBox_35.setObjectName("groupBox_35")
        self.verticalLayout_82 = QtWidgets.QVBoxLayout(self.groupBox_35)
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_5)
        self.verticalLayout_82.addWidget(self.radioButton_5)
        self.Spectral_transform_standard = QtWidgets.QRadioButton(self.groupBox_35)
        self.Spectral_transform_standard.setEnabled(True)
        self.Spectral_transform_standard.setObjectName("Spectral_transform_standard")
        self.buttonGroup.addButton(self.Spectral_transform_standard)
        self.verticalLayout_82.addWidget(self.Spectral_transform_standard)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout_82.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout_82.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout_82.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.verticalLayout_82.addWidget(self.radioButton_4)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.verticalLayout_82.addLayout(self.horizontalLayout_75)
        self.verticalLayout_81.addWidget(self.groupBox_35)
        spacerItem1 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_81.addItem(spacerItem1)
        self.horizontalLayout_64.addLayout(self.verticalLayout_81)
        self.mplWidgetSpectral_6 = QMatplotlibWidget(self.tab_44)
        self.mplWidgetSpectral_6.setObjectName("mplWidgetSpectral_6")
        self.horizontalLayout_64.addWidget(self.mplWidgetSpectral_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_64, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_44, "")
        self.gridLayout.addWidget(self.tabWidget_4, 2, 0, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Spectral Preprocessing and Transform"))
        self.groupBox.setTitle(_translate("Form", "Spectral Preprocessing and Transform"))
        self.label_70.setText(_translate("Form", "Spectra"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.label_72.setText(_translate("Form", "Output"))
        self.groupBox_34.setTitle(_translate("Form", "Category"))
        self.Soil_property.setText(_translate("Form", "Soil Property Plot"))
        self.Transform_box_cox.setText(_translate("Form", "Transform Box-Cox"))
        self.Transform_log.setText(_translate("Form", "Transform Log"))
        self.Transform_standard.setText(_translate("Form", "Transform Standard Normal"))
        self.Plot_spectra.setText(_translate("Form", "PLOT SPECTRA"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_29), _translate("Form", "Spectral Preprocessing"))
        self.groupBox_35.setTitle(_translate("Form", "Category"))
        self.radioButton_5.setText(_translate("Form", "Spectral Transform 1/Log"))
        self.Spectral_transform_standard.setText(_translate("Form", "Spectral Transform Standard Scalar"))
        self.radioButton.setText(_translate("Form", "Spectral Transform Standard Normal Variate"))
        self.radioButton_2.setText(_translate("Form", "Spectral Derivative"))
        self.radioButton_3.setText(_translate("Form", "Spectral Smoothing Savitsky-Golay"))
        self.radioButton_4.setText(_translate("Form", "Correlation of property with wavelength"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_44), _translate("Form", "Spectral Transform"))
        self.pushButton_4.setText(_translate("Form", "Browse"))

from Ui.qmatplotlibwidget import QMatplotlibWidget
