# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Proximal\ProximalAnalysisTool\Ui\SpectralPre_TransformUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 535)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.togglePropertyChk = QtWidgets.QCheckBox(self.groupBox)
        self.togglePropertyChk.setObjectName("togglePropertyChk")
        self.gridLayout.addWidget(self.togglePropertyChk, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_44 = QtWidgets.QWidget()
        self.tab_44.setObjectName("tab_44")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_44)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.verticalLayout_81 = QtWidgets.QVBoxLayout()
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.groupBox_35 = QtWidgets.QGroupBox(self.tab_44)
        self.groupBox_35.setObjectName("groupBox_35")
        self.verticalLayout_82 = QtWidgets.QVBoxLayout(self.groupBox_35)
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_5)
        self.verticalLayout_82.addWidget(self.radioButton_5)
        self.Spectral_transform_standard = QtWidgets.QRadioButton(self.groupBox_35)
        self.Spectral_transform_standard.setEnabled(True)
        self.Spectral_transform_standard.setObjectName("Spectral_transform_standard")
        self.buttonGroup.addButton(self.Spectral_transform_standard)
        self.verticalLayout_82.addWidget(self.Spectral_transform_standard)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup.addButton(self.radioButton)
        self.verticalLayout_82.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout_82.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.verticalLayout_82.addWidget(self.radioButton_3)
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.verticalLayout_82.addLayout(self.horizontalLayout_75)
        self.verticalLayout_81.addWidget(self.groupBox_35)
        spacerItem = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_81.addItem(spacerItem)
        self.horizontalLayout_64.addLayout(self.verticalLayout_81)
        self.mplWidgetSpectral_6 = QMatplotlibWidget(self.tab_44)
        self.mplWidgetSpectral_6.setObjectName("mplWidgetSpectral_6")
        self.horizontalLayout_64.addWidget(self.mplWidgetSpectral_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_64, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_44, "")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.gridLayout_57 = QtWidgets.QGridLayout(self.tab_29)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.groupBox_34 = QtWidgets.QGroupBox(self.tab_29)
        self.groupBox_34.setObjectName("groupBox_34")
        self.verticalLayout_80 = QtWidgets.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_34)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        self.label_76.setObjectName("label_76")
        self.verticalLayout.addWidget(self.label_76)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_77 = QtWidgets.QLabel(self.groupBox_2)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_3.addWidget(self.label_77)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_9.setChecked(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.gridLayout_4.addWidget(self.radioButton_9, 0, 1, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.gridLayout_4.addWidget(self.radioButton_8, 0, 0, 1, 1)
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_10.setObjectName("radioButton_10")
        self.gridLayout_4.addWidget(self.radioButton_10, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_80.addWidget(self.groupBox_2)
        self.horizontalLayout_62 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_62.setObjectName("horizontalLayout_62")
        self.verticalLayout_80.addLayout(self.horizontalLayout_62)
        self.verticalLayout_79.addWidget(self.groupBox_34)
        spacerItem2 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_79.addItem(spacerItem2)
        self.horizontalLayout_61.addLayout(self.verticalLayout_79)
        self.mplWidgetSpectral_5 = QMatplotlibWidget(self.tab_29)
        self.mplWidgetSpectral_5.setObjectName("mplWidgetSpectral_5")
        self.horizontalLayout_61.addWidget(self.mplWidgetSpectral_5)
        self.gridLayout_57.addLayout(self.horizontalLayout_61, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_29, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox_36 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_36.setObjectName("groupBox_36")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_36)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.selectWvFamilyLbl = QtWidgets.QLabel(self.groupBox_36)
        self.selectWvFamilyLbl.setObjectName("selectWvFamilyLbl")
        self.gridLayout_5.addWidget(self.selectWvFamilyLbl, 0, 0, 1, 1)
        self.wvFamilyCmb = QtWidgets.QComboBox(self.groupBox_36)
        self.wvFamilyCmb.setObjectName("wvFamilyCmb")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.wvFamilyCmb.addItem("")
        self.gridLayout_5.addWidget(self.wvFamilyCmb, 1, 0, 1, 1)
        self.WvLbl = QtWidgets.QLabel(self.groupBox_36)
        self.WvLbl.setObjectName("WvLbl")
        self.gridLayout_5.addWidget(self.WvLbl, 2, 0, 1, 1)
        self.WvCmb = QtWidgets.QComboBox(self.groupBox_36)
        self.WvCmb.setObjectName("WvCmb")
        self.WvCmb.addItem("")
        self.gridLayout_5.addWidget(self.WvCmb, 3, 0, 1, 1)
        self.lvlDecompLbl = QtWidgets.QLabel(self.groupBox_36)
        self.lvlDecompLbl.setObjectName("lvlDecompLbl")
        self.gridLayout_5.addWidget(self.lvlDecompLbl, 4, 0, 1, 1)
        self.lvlDecompSpb = QtWidgets.QSpinBox(self.groupBox_36)
        self.lvlDecompSpb.setMinimum(1)
        self.lvlDecompSpb.setMaximum(4)
        self.lvlDecompSpb.setProperty("value", 4)
        self.lvlDecompSpb.setObjectName("lvlDecompSpb")
        self.gridLayout_5.addWidget(self.lvlDecompSpb, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_36)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 6, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.padSmoothRbn = QtWidgets.QRadioButton(self.groupBox_36)
        self.padSmoothRbn.setChecked(True)
        self.padSmoothRbn.setObjectName("padSmoothRbn")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.padSmoothRbn)
        self.horizontalLayout.addWidget(self.padSmoothRbn)
        self.padReflRbn = QtWidgets.QRadioButton(self.groupBox_36)
        self.padReflRbn.setObjectName("padReflRbn")
        self.buttonGroup_2.addButton(self.padReflRbn)
        self.horizontalLayout.addWidget(self.padReflRbn)
        self.padSymmRbn = QtWidgets.QRadioButton(self.groupBox_36)
        self.padSymmRbn.setObjectName("padSymmRbn")
        self.buttonGroup_2.addButton(self.padSymmRbn)
        self.horizontalLayout.addWidget(self.padSymmRbn)
        self.gridLayout_5.addLayout(self.horizontalLayout, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 8, 1, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_36, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget_4, 3, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Spectral Preprocessing and Transform"))
        self.groupBox.setTitle(_translate("Form", "Spectral Preprocessing and Transform"))
        self.label_70.setText(_translate("Form", "Spectra"))
        self.pushButton_4.setText(_translate("Form", "Browse"))
        self.togglePropertyChk.setText(_translate("Form", "Target Properties"))
        self.pushButton_5.setText(_translate("Form", "Browse"))
        self.label_72.setText(_translate("Form", "Output"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.groupBox_35.setTitle(_translate("Form", "Category"))
        self.radioButton_5.setText(_translate("Form", "1/Log"))
        self.Spectral_transform_standard.setText(_translate("Form", "Standard Scalar"))
        self.radioButton.setText(_translate("Form", "Standard Normal Variate"))
        self.radioButton_2.setText(_translate("Form", "First Derivative"))
        self.radioButton_3.setText(_translate("Form", "Smoothing Savitsky-Golay"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_44), _translate("Form", "Spectral Transform"))
        self.groupBox_34.setTitle(_translate("Form", "Category"))
        self.label_76.setText(_translate("Form", "Select property"))
        self.label_77.setText(_translate("Form", "Transform"))
        self.radioButton_9.setText(_translate("Form", "Transform Log"))
        self.radioButton_8.setText(_translate("Form", "Box-cox"))
        self.radioButton_10.setText(_translate("Form", "None"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_29), _translate("Form", "Property Preprocessing"))
        self.groupBox_36.setTitle(_translate("Form", "Wavelet"))
        self.selectWvFamilyLbl.setText(_translate("Form", "Select Wavelet Family :"))
        self.wvFamilyCmb.setItemText(0, _translate("Form", "--Select--"))
        self.wvFamilyCmb.setItemText(1, _translate("Form", "haar"))
        self.wvFamilyCmb.setItemText(2, _translate("Form", "db"))
        self.wvFamilyCmb.setItemText(3, _translate("Form", "sym"))
        self.wvFamilyCmb.setItemText(4, _translate("Form", "coif"))
        self.wvFamilyCmb.setItemText(5, _translate("Form", "bior"))
        self.wvFamilyCmb.setItemText(6, _translate("Form", "rbio"))
        self.wvFamilyCmb.setItemText(7, _translate("Form", "dmey"))
        self.wvFamilyCmb.setItemText(8, _translate("Form", "gaus"))
        self.wvFamilyCmb.setItemText(9, _translate("Form", "mexh"))
        self.wvFamilyCmb.setItemText(10, _translate("Form", "morl"))
        self.wvFamilyCmb.setItemText(11, _translate("Form", "cgau"))
        self.wvFamilyCmb.setItemText(12, _translate("Form", "shan"))
        self.wvFamilyCmb.setItemText(13, _translate("Form", "fbsp"))
        self.wvFamilyCmb.setItemText(14, _translate("Form", "cmor"))
        self.WvLbl.setText(_translate("Form", "Select Wavelet"))
        self.WvCmb.setItemText(0, _translate("Form", "--Select--"))
        self.lvlDecompLbl.setText(_translate("Form", "Level of decomposition :"))
        self.label_4.setText(_translate("Form", "Padding :"))
        self.padSmoothRbn.setText(_translate("Form", "Smooth"))
        self.padReflRbn.setText(_translate("Form", "Reflect"))
        self.padSymmRbn.setText(_translate("Form", "Symmetric"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab), _translate("Form", "Wavelet Transform"))

from ProximalAnalysisTool.Ui.qmatplotlibwidget import QMatplotlibWidget