# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui\TimeseriesUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1053, 512)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 2, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setObjectName("label_71")
        self.gridLayout.addWidget(self.label_71, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setEnabled(True)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_29)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab_29)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_79.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.groupBox_34 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_34.setObjectName("groupBox_34")
        self.verticalLayout_80 = QtWidgets.QVBoxLayout(self.groupBox_34)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.rb_sep_all_5 = QtWidgets.QRadioButton(self.groupBox_34)
        self.rb_sep_all_5.setChecked(True)
        self.rb_sep_all_5.setObjectName("rb_sep_all_5")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rb_sep_all_5)
        self.verticalLayout_80.addWidget(self.rb_sep_all_5)
        self.rb_sep_compare_5 = QtWidgets.QRadioButton(self.groupBox_34)
        self.rb_sep_compare_5.setObjectName("rb_sep_compare_5")
        self.buttonGroup.addButton(self.rb_sep_compare_5)
        self.verticalLayout_80.addWidget(self.rb_sep_compare_5)
        self.radioClassDistribute = QtWidgets.QRadioButton(self.groupBox_34)
        self.radioClassDistribute.setChecked(False)
        self.radioClassDistribute.setObjectName("radioClassDistribute")
        self.buttonGroup.addButton(self.radioClassDistribute)
        self.verticalLayout_80.addWidget(self.radioClassDistribute)
        self.label_73 = QtWidgets.QLabel(self.groupBox_34)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_80.addWidget(self.label_73)
        self.x1CoordEdit_11 = QtWidgets.QLineEdit(self.groupBox_34)
        self.x1CoordEdit_11.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_11.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_11.setSizePolicy(sizePolicy)
        self.x1CoordEdit_11.setObjectName("x1CoordEdit_11")
        self.verticalLayout_80.addWidget(self.x1CoordEdit_11)
        self.groupBox_42 = QtWidgets.QGroupBox(self.groupBox_34)
        self.groupBox_42.setObjectName("groupBox_42")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_42)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.label_58 = QtWidgets.QLabel(self.groupBox_42)
        self.label_58.setEnabled(False)
        self.label_58.setObjectName("label_58")
        self.horizontalLayout_78.addWidget(self.label_58)
        self.comboBox_25 = QtWidgets.QComboBox(self.groupBox_42)
        self.comboBox_25.setEnabled(False)
        self.comboBox_25.setObjectName("comboBox_25")
        self.horizontalLayout_78.addWidget(self.comboBox_25)
        self.verticalLayout_3.addLayout(self.horizontalLayout_78)
        self.horizontalLayout_79 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_79.setObjectName("horizontalLayout_79")
        self.label_59 = QtWidgets.QLabel(self.groupBox_42)
        self.label_59.setEnabled(False)
        self.label_59.setObjectName("label_59")
        self.horizontalLayout_79.addWidget(self.label_59)
        self.comboBox_26 = QtWidgets.QComboBox(self.groupBox_42)
        self.comboBox_26.setEnabled(False)
        self.comboBox_26.setObjectName("comboBox_26")
        self.horizontalLayout_79.addWidget(self.comboBox_26)
        self.verticalLayout_3.addLayout(self.horizontalLayout_79)
        self.verticalLayout_80.addWidget(self.groupBox_42)
        self.verticalLayout_79.addWidget(self.groupBox_34)
        spacerItem = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_79.addItem(spacerItem)
        self.mplWidgetSpectral_5 = QMatplotlibWidget(self.splitter)
        self.mplWidgetSpectral_5.setObjectName("mplWidgetSpectral_5")
        self.verticalLayout_2.addWidget(self.splitter)
        self.tabWidget_4.addTab(self.tab_29, "")
        self.tab_44 = QtWidgets.QWidget()
        self.tab_44.setObjectName("tab_44")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_44)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter_2 = QtWidgets.QSplitter(self.tab_44)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget1 = QtWidgets.QWidget(self.splitter_2)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_81 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_81.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.groupBox_35 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_35.setObjectName("groupBox_35")
        self.verticalLayout_82 = QtWidgets.QVBoxLayout(self.groupBox_35)
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.radioFeatureVar = QtWidgets.QRadioButton(self.groupBox_35)
        self.radioFeatureVar.setEnabled(True)
        self.radioFeatureVar.setObjectName("radioFeatureVar")
        self.buttonGroup.addButton(self.radioFeatureVar)
        self.verticalLayout_82.addWidget(self.radioFeatureVar)
        self.label_75 = QtWidgets.QLabel(self.groupBox_35)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_82.addWidget(self.label_75)
        self.x1CoordEdit_13 = QtWidgets.QLineEdit(self.groupBox_35)
        self.x1CoordEdit_13.setEnabled(False)
        self.x1CoordEdit_13.setObjectName("x1CoordEdit_13")
        self.verticalLayout_82.addWidget(self.x1CoordEdit_13)
        self.verticalLayout_81.addWidget(self.groupBox_35)
        spacerItem1 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_81.addItem(spacerItem1)
        self.mplWidgetSpectral_6 = QMatplotlibWidget(self.splitter_2)
        self.mplWidgetSpectral_6.setObjectName("mplWidgetSpectral_6")
        self.verticalLayout_4.addWidget(self.splitter_2)
        self.tabWidget_4.addTab(self.tab_44, "")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_33)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.splitter_3 = QtWidgets.QSplitter(self.tab_33)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.widget2 = QtWidgets.QWidget(self.splitter_3)
        self.widget2.setObjectName("widget2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_38 = QtWidgets.QGroupBox(self.widget2)
        self.groupBox_38.setObjectName("groupBox_38")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_38)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioFTEST_5 = QtWidgets.QRadioButton(self.groupBox_38)
        self.radioFTEST_5.setChecked(False)
        self.radioFTEST_5.setObjectName("radioFTEST_5")
        self.buttonGroup.addButton(self.radioFTEST_5)
        self.verticalLayout_6.addWidget(self.radioFTEST_5)
        self.radioSEP_5 = QtWidgets.QRadioButton(self.groupBox_38)
        self.radioSEP_5.setObjectName("radioSEP_5")
        self.buttonGroup.addButton(self.radioSEP_5)
        self.verticalLayout_6.addWidget(self.radioSEP_5)
        self.radioMUTUAL_5 = QtWidgets.QRadioButton(self.groupBox_38)
        self.radioMUTUAL_5.setObjectName("radioMUTUAL_5")
        self.buttonGroup.addButton(self.radioMUTUAL_5)
        self.verticalLayout_6.addWidget(self.radioMUTUAL_5)
        self.label_67 = QtWidgets.QLabel(self.groupBox_38)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_6.addWidget(self.label_67)
        self.x1CoordEdit_10 = QtWidgets.QLineEdit(self.groupBox_38)
        self.x1CoordEdit_10.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_10.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_10.setSizePolicy(sizePolicy)
        self.x1CoordEdit_10.setObjectName("x1CoordEdit_10")
        self.verticalLayout_6.addWidget(self.x1CoordEdit_10)
        self.radioTREE_5 = QtWidgets.QRadioButton(self.groupBox_38)
        self.radioTREE_5.setObjectName("radioTREE_5")
        self.buttonGroup.addButton(self.radioTREE_5)
        self.verticalLayout_6.addWidget(self.radioTREE_5)
        self.verticalLayout_7.addWidget(self.groupBox_38)
        self.groupBox_39 = QtWidgets.QGroupBox(self.widget2)
        self.groupBox_39.setObjectName("groupBox_39")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_39)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_67 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_67.setObjectName("horizontalLayout_67")
        self.label_63 = QtWidgets.QLabel(self.groupBox_39)
        self.label_63.setEnabled(False)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_67.addWidget(self.label_63)
        self.comboBox_classA_8 = QtWidgets.QComboBox(self.groupBox_39)
        self.comboBox_classA_8.setEnabled(False)
        self.comboBox_classA_8.setObjectName("comboBox_classA_8")
        self.horizontalLayout_67.addWidget(self.comboBox_classA_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_67)
        self.horizontalLayout_68 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_68.setObjectName("horizontalLayout_68")
        self.label_64 = QtWidgets.QLabel(self.groupBox_39)
        self.label_64.setEnabled(False)
        self.label_64.setObjectName("label_64")
        self.horizontalLayout_68.addWidget(self.label_64)
        self.comboBox_classB_8 = QtWidgets.QComboBox(self.groupBox_39)
        self.comboBox_classB_8.setEnabled(False)
        self.comboBox_classB_8.setObjectName("comboBox_classB_8")
        self.horizontalLayout_68.addWidget(self.comboBox_classB_8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_68)
        self.verticalLayout_7.addWidget(self.groupBox_39)
        spacerItem2 = QtWidgets.QSpacerItem(20, 178, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.widget_feature_5 = QMatplotlibWidget(self.splitter_3)
        self.widget_feature_5.setObjectName("widget_feature_5")
        self.verticalLayout_8.addWidget(self.splitter_3)
        self.tabWidget_4.addTab(self.tab_33, "")
        self.gridLayout.addWidget(self.tabWidget_4, 3, 0, 1, 3)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Timeseries Analysis"))
        self.groupBox.setTitle(_translate("Form", "Time Series Analysis"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.pushButton_5.setText(_translate("Form", "Browse"))
        self.label_72.setText(_translate("Form", "Output"))
        self.label_70.setText(_translate("Form", "Spectra"))
        self.label_71.setText(_translate("Form", "Metadata"))
        self.pushButton_4.setText(_translate("Form", "Browse"))
        self.groupBox_34.setTitle(_translate("Form", "Category"))
        self.rb_sep_all_5.setText(_translate("Form", "All Spectra (Mean & Standard Deviation)"))
        self.rb_sep_compare_5.setText(_translate("Form", "Compare Two Class Spectra"))
        self.radioClassDistribute.setText(_translate("Form", "Continum Removal"))
        self.label_73.setText(_translate("Form", "Baseline"))
        self.x1CoordEdit_11.setText(_translate("Form", "0.93"))
        self.groupBox_42.setTitle(_translate("Form", "Compare"))
        self.label_58.setText(_translate("Form", "Class A"))
        self.label_59.setText(_translate("Form", "Class B"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_29), _translate("Form", "Spectral View"))
        self.groupBox_35.setTitle(_translate("Form", "Category"))
        self.radioFeatureVar.setText(_translate("Form", "Band Plot"))
        self.label_75.setText(_translate("Form", "Wavelength"))
        self.x1CoordEdit_13.setText(_translate("Form", "400"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_44), _translate("Form", "Distribution"))
        self.groupBox_38.setTitle(_translate("Form", "Methods"))
        self.radioFTEST_5.setText(_translate("Form", "Spectral Discrimination Index"))
        self.radioSEP_5.setText(_translate("Form", "Oneway Anova"))
        self.radioMUTUAL_5.setText(_translate("Form", "Tukey’s multi-comparison"))
        self.label_67.setText(_translate("Form", "Wavelength"))
        self.x1CoordEdit_10.setText(_translate("Form", "400"))
        self.radioTREE_5.setText(_translate("Form", "Kruskal Wallis Non-Parametric H Test"))
        self.groupBox_39.setTitle(_translate("Form", "Compare"))
        self.label_63.setText(_translate("Form", "Class A"))
        self.label_64.setText(_translate("Form", "Class B"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_33), _translate("Form", "Band Seperability"))

from Ui.qmatplotlibwidget import QMatplotlibWidget
