# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Ui\Univariate_RegressionUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1070, 506)
        self.gridLayout_6 = QtWidgets.QGridLayout(Form)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_70 = QtWidgets.QLabel(self.groupBox)
        self.label_70.setObjectName("label_70")
        self.gridLayout.addWidget(self.label_70, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.groupBox)
        self.label_71.setObjectName("label_71")
        self.gridLayout.addWidget(self.label_71, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.groupBox)
        self.label_72.setObjectName("label_72")
        self.gridLayout.addWidget(self.label_72, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.groupBox)
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_44 = QtWidgets.QWidget()
        self.tab_44.setObjectName("tab_44")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_44)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.splitter = QtWidgets.QSplitter(self.tab_44)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.gridLayout_2.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.gridLayout_2.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout_2.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.buttonGroup.addButton(self.radioButton_3)
        self.gridLayout_2.addWidget(self.radioButton_3, 1, 1, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.gridLayout_2.addWidget(self.radioButton_5, 2, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.gridLayout_2.addWidget(self.radioButton_6, 2, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_76 = QtWidgets.QLabel(self.groupBox_2)
        self.label_76.setObjectName("label_76")
        self.verticalLayout.addWidget(self.label_76)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_77 = QtWidgets.QLabel(self.groupBox_2)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_3.addWidget(self.label_77)
        self.x1CoordEdit_14 = QtWidgets.QLineEdit(self.groupBox_2)
        self.x1CoordEdit_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.x1CoordEdit_14.sizePolicy().hasHeightForWidth())
        self.x1CoordEdit_14.setSizePolicy(sizePolicy)
        self.x1CoordEdit_14.setMaxLength(3)
        self.x1CoordEdit_14.setObjectName("x1CoordEdit_14")
        self.verticalLayout_3.addWidget(self.x1CoordEdit_14)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_35 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_35.setObjectName("groupBox_35")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_35)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_75 = QtWidgets.QLabel(self.groupBox_35)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_2.addWidget(self.label_75)
        self.wavelengthCmb = QtWidgets.QComboBox(self.groupBox_35)
        self.wavelengthCmb.setObjectName("wavelengthCmb")
        self.verticalLayout_2.addWidget(self.wavelengthCmb)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.groupBox_35)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.mplWidgetSpectral_6 = QMatplotlibWidget(self.splitter)
        self.mplWidgetSpectral_6.setObjectName("mplWidgetSpectral_6")
        self.verticalLayout_7.addWidget(self.splitter)
        self.tabWidget_4.addTab(self.tab_44, "")
        self.verticalLayout_8.addWidget(self.tabWidget_4)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Timeseries Analysis"))
        self.groupBox.setTitle(_translate("Form", "Regression"))
        self.label_70.setText(_translate("Form", "Spectra"))
        self.pushButton_4.setText(_translate("Form", "Browse"))
        self.label_71.setText(_translate("Form", "Metadata"))
        self.pushButton_5.setText(_translate("Form", "Browse"))
        self.label_72.setText(_translate("Form", "Output"))
        self.pushButton_6.setText(_translate("Form", "Save"))
        self.groupBox_3.setTitle(_translate("Form", "Regression Model"))
        self.radioButton.setText(_translate("Form", "Linear Regression"))
        self.radioButton_2.setText(_translate("Form", "Logistic Regression"))
        self.radioButton_4.setText(_translate("Form", "Lasso Regression"))
        self.radioButton_3.setText(_translate("Form", "Ridge Regression"))
        self.radioButton_5.setText(_translate("Form", "Polynomial Regression"))
        self.radioButton_6.setText(_translate("Form", "Bayesian Linear Regression"))
        self.groupBox_2.setTitle(_translate("Form", "Dependent Variable (y)"))
        self.label_76.setText(_translate("Form", "Select target property"))
        self.label_77.setText(_translate("Form", "Train Size (%)"))
        self.x1CoordEdit_14.setText(_translate("Form", "60"))
        self.groupBox_35.setTitle(_translate("Form", "Independent variable (x)"))
        self.label_75.setText(_translate("Form", "Select band/variable"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_44), _translate("Form", "Univariate Regression"))

from Ui.qmatplotlibwidget import QMatplotlibWidget
